INSERT INTO SAMS.BR_G10_CONFIRM_RESULT(PUPIL_ID, SCHOOL_YEAR_ID, HIGH_SCHOOL_CODE, HIGH_SCHOOL_ID, JUNIOR_SCHOOL_ID, 
										JUNIOR_CLASS_ID, JUNIOR_SCHOOL_YEAR_ID, MARK, JUNIOR_STUDY_RANK_ID, JUNIOR_CONDUCT_RANK_ID, 
										EDUCATION_TYPE_ID, EDUCATION_LEVEL_ID, METHOD_ID, IS_EXTERNAL, DESCRIPTION, SORT_ORDER, 
										CREATED_DATE, CREATED_BY, MODIFY_DATE, MODIFY_BY, ROW_VERSION, IS_DELETED, IS_ACTIVE, IS_DEFAULT) 
VALUES('012196578', 24, '2223____', 10042302, 10031798, 60498,21, NULL, -1, -1, 4, 4, 2, 0, NULL, NULL,sysdate
      , 'administrator', NULL, NULL, NULL, 0, 1, NULL);