SELECT DISTINCT
    SU.USERNAME,
    organname CO_QUAN,
    schoolname TRUONG,
		SU.FULLNAME HO_TEN,
		SU.FIRSTNAME TEN,
		SU.LASTNAME HO,
		SU.GENDER GIOI_TINH,
		to_char(SU.birthday,'DD/MM/YYYY') NGAY_SINH,

		SU.EMAIL
	
	
	FROM SAMS.SYS_USER SU
   JOIN SAMS.SYS_USER_TEACHSCHOOL SUT ON SU.USERNAME = SUT.USERNAME
   --JOIN EDU_SCHOOL ES ON SUT.SCHOOLID = ES.SCHOOLID
   JOIN SAMS.SYS_POSITION SP ON SP.POSITIONID = SU.POSITIONID
   LEFT JOIN SAMS.SYS_DEPARTMENT SD ON SU.DEPARTMENTID = SD.DEPARTMENTID
   LEFT JOIN SAMS.SYS_WORKINGPOSITION SW ON SU.WORKINGPOSITIONID = SW.WORKINGPOSITIONID
   LEFT JOIN SAMS.SYS_USER_SUBJECT ON SYS_USER_SUBJECT.USERNAME = SUT.USERNAME
  JOIN SAMS.edu_school
  ON sams.edu_school.schoolid = SUT.schoolid
  JOIN sams.md_organ
  ON sams.md_organ.organid = SAMS.edu_school.organid
	WHERE SU.ISDELETED = 0 
   AND SU.ISACTIVE = 1 
   AND SU.ORGANID <> -1
   AND SU.ISDELETED = 0
  AND SAMS.edu_school.isactive = 1
  AND SAMS.edu_school.isdeleted=  0
  AND su.idcard IS NULL
    ORDER BY NLSSORT(NLS_LOWER(SU.FIRSTNAME, 'NLS_SORT=vietnamese'),'NLS_SORT=vietnamese'),
               NLSSORT(NLS_LOWER(SU.LASTNAME, 'NLS_SORT=vietnamese'),'NLS_SORT=vietnamese'),
               to_char(SU.birthday,'DD/MM/YYYY')