
SELECT 
--  PUPILID MA_HS

  SAMS.MP_EDUSCHOOL.MOETSCHOOLID MA_TRUONG
  ,SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID MA_LOP
  ,FULLNAME TEN_HS
  ,TO_CHAR(BIRTHDAY,'DD/MM/YYYY') NGAY_SINH
  ,DECODE(gender,0,'01','02') GIOI_TINH
  ,'01' TRANG_THAI
  ,' ' LY_DO_THOI_HOC
  ,SAMS.MP_EDUETHNICITY.MOETETHNICITYID DAN_TOC
  ,CASE WHEN EDU_PUPIL.NATIONLATYID <> 250 THEN ' ' ELSE '704' END QUOC_GIA
  ,SAMS.MP_EDUPROVINCE.MOETPROVINCEID TINH
  ,SAMS.MP_EDUDISTRICT.MOETDISTRICTID HUYEN
  ,' ' XA
  ,BIRTHPLACE NOI_SINH
  ,HAMLETNAME XOM
  ,PERMANENTFULLADDRESS DIA_CHI
  ,CONTACTPHONE SDT_LIEN_HE
  ,' ' KHU_VUC
--  ,' ' HINH_THUC_HOC_TAP
  ,SAMS.MP_EDUDISABILITYTYPE.MOETDISABILITYTYPEID LOAI_KHUYET_TAT
  ,(
   SELECT 
 LISTAGG(CAST(MP_EDUPOLICYOBJECTTYPE.MOETPOLICYOBJECTTYPEID  AS VARCHAR2(1800))  ,', ') WITHIN GROUP (ORDER BY MP_EDUPOLICYOBJECTTYPE.MOETPOLICYOBJECTTYPEID)
  FROM SAMS.EDU_PUPIL_POLICYOBJECT 
    JOIN SAMS.MP_EDUPOLICYOBJECTTYPE
      ON MP_EDUPOLICYOBJECTTYPE.POLICYOBJECTTYPEID = EDU_PUPIL_POLICYOBJECT.POLICYOBJECTTYPEID
  WHERE PUPILID = SAMS.EDU_PUPIL.PUPILID
  )DOI_TUONG_CS
  ,SAMS.EDU_PUPIL.IDCARD CMND
  ,IDCARDPROVINCE.PROVINCENAME NOI_CAP
  ,TO_CHAR(SAMS.EDU_PUPIL.IDCARDISSUEDATE,'DD/MM/YYYY') NGAY_CAP
  ,CASE WHEN SAMS.EDU_PUPIL.ismemberofyouthunion = 1 THEN 'x' END LA_DOI_VIEN
  ,CASE WHEN SAMS.EDU_PUPIL.ISMEMBEROFJUNIORYOUTHUNION = 1 THEN 'x' END LA_DOAN_VIEN
  ,' ' CO_ME_LA_DAN_TOC
  ,' ' CO_CHA_LA_DAN_TOC
  ,' ' LUU_BAN
  ,SAMS.EDU_PUPIL.FATHERFULLNAME HO_TEN_CHA
  ,CASE WHEN FATHERJOB.ISOTHER = 1 THEN SAMS.EDU_PUPIL.FATHERJOBTITLE ELSE FATHERJOB.JOBNAME END NGHE_NGHIEP_CHA
  ,TO_CHAR(SAMS.EDU_PUPIL.FATHERBIRTHDAY,'YYYY') NAM_SINH_CHA
  ,SAMS.EDU_PUPIL.MOTHERFULLNAME HO_TEN_ME
  ,CASE WHEN MOTHERJOB.ISOTHER = 1 THEN SAMS.EDU_PUPIL.MOTHERJOBTITLE ELSE MOTHERJOB.JOBNAME END NGHE_NGHIEP_ME
  ,TO_CHAR(SAMS.EDU_PUPIL.MOTHERBIRTHDAY,'YYYY') NAM_SINH_ME
  ,SAMS.EDU_PUPIL.GUARDIANFULLNAME HO_TEN_GH
  ,CASE WHEN GUARDIANJOB.ISOTHER = 1 THEN SAMS.EDU_PUPIL.GUARDIANJOBTITLE ELSE GUARDIANJOB.JOBNAME END NGHE_NGHIEP_GH
  ,TO_CHAR(SAMS.EDU_PUPIL.GUARDIANBIRTHDAY,'YYYY') NAM_SINH_GH
  FROM SAMS.EDU_PUPIL_STUDYTIMELINE
  
LEFT JOIN SAMS.EDU_PUPIL
  ON SAMS.EDU_PUPIL.PUPILID = SAMS.EDU_PUPIL_STUDYTIMELINE.PUPILID
LEFT JOIN SAMS.EDU_SCHOOL
  ON SAMS.EDU_SCHOOL.SCHOOLID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLID
LEFT JOIN SAMS.EDU_SCHOOLCLASS_NEW
  ON SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID
LEFT JOIN SAMS.EDU_CLASS
  ON SAMS.EDU_CLASS.CLASSID = SAMS.EDU_SCHOOLCLASS_NEW.CLASSID
LEFT JOIN SAMS.MP_EDUSCHOOL
  ON SAMS.MP_EDUSCHOOL.SCHOOLID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLID
  AND SAMS.MP_EDUSCHOOL.EDUCATIONLEVELID = SAMS.EDU_CLASS.EDUCATIONLEVELID
LEFT JOIN SAMS.MP_EDUCLASS
  ON SAMS.MP_EDUCLASS.CLASSID = SAMS.EDU_SCHOOLCLASS_NEW.CLASSID
LEFT JOIN SAMS.EDU_PUPILSTATUS
  ON SAMS.EDU_PUPILSTATUS.PUPILSTATUSID = SAMS.EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID
LEFT  JOIN SAMS.MD_NATIONLATY
  ON SAMS.MD_NATIONLATY.NATIONLATYID = SAMS.EDU_PUPIL.NATIONLATYID
LEFT JOIN SAMS.MD_PROVINCE
  ON SAMS.MD_PROVINCE.PROVINCEID = SAMS.EDU_PUPIL.PERMANENTPROVINCEID
LEFT JOIN SAMS.MP_EDUPROVINCE
  ON SAMS.MP_EDUPROVINCE.PROVINCEID = SAMS.EDU_PUPIL.PERMANENTPROVINCEID
   LEFT   JOIN SAMS.MP_EDUDISTRICT
  ON SAMS.MP_EDUDISTRICT.DISTRICTID = SAMS.EDU_PUPIL.PERMANENTDISTRICTID
 LEFT   JOIN SAMS.MD_WARD
  ON SAMS.MD_WARD.WARDID = SAMS.EDU_PUPIL.PERMANENTWARDID
LEFT  JOIN SAMS.MD_HAMLET
  ON SAMS.MD_HAMLET.HAMLETID = SAMS.EDU_PUPIL.PERMANENTHAMLETID
LEFT JOIN SAMS.PL_ETHNICITY
  ON SAMS.PL_ETHNICITY.ETHNICITYID = SAMS.EDU_PUPIL.ETHNICITYID
LEFT JOIN SAMS.MP_EDUETHNICITY
  ON SAMS.MP_EDUETHNICITY.ETHNICITYID = SAMS.EDU_PUPIL.ETHNICITYID
LEFT JOIN SAMS.MD_PROVINCE IDCARDPROVINCE
  ON SAMS.EDU_PUPIL.idcardissueplaceid = IDCARDPROVINCE.provinceid
LEFT JOIN SAMS.MD_JOB FATHERJOB
  ON FATHERJOB.JOBID = SAMS.EDU_PUPIL.FATHERJOBID
  LEFT JOIN SAMS.MD_JOB MOTHERJOB
  ON MOTHERJOB.JOBID = SAMS.EDU_PUPIL.MOTHERJOBID
  LEFT JOIN SAMS.MD_JOB GUARDIANJOB
  ON GUARDIANJOB.JOBID = SAMS.EDU_PUPIL.GUARDIANJOBID
LEFT JOIN SAMS.MP_EDUDISABILITYTYPE
  ON SAMS.MP_EDUDISABILITYTYPE.DISABILITYTYPEID = SAMS.EDU_PUPIL.DISABILITYTYPEID
WHERE 
SAMS.EDU_PUPIL.ISACTIVE = 1
  AND SAMS.EDU_PUPIL.ISDELETED = 0
   AND SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 2
  AND SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 2
  AND SAMS.EDU_SCHOOLCLASS_NEW.isactive = 1
  AND SAMS.EDU_SCHOOLCLASS_NEW.isdeleted = 0
  AND SAMS.EDU_CLASS.EDUCATIONLEVELID = 2
  AND SAMS.EDU_CLASS.isactive = 1
  AND SAMS.EDU_CLASS.isdeleted = 0
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID = 1
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.isactive = 1
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.isdeleted = 0

AND edu_school.schoolid NOT IN (
  SELECT schoolid   FROM SAMS.edu_school
  WHERE UPPER(schoolname) LIKE '%T? DO%')
 
    AND edu_school.schoolid NOT IN (1524,1530,10112318,1541,1525,1515,1470,1469,1528)
--  AND edu_school.schoolid NOT IN (
--  SELECT CONFIGVALUE   FROM SAMS.SYS_APPCONFIG
--  WHERE APPCONFIGID = 'RPT_LISTOFNON - STATISTICSSCHOOL')
    AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 2
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 2
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
  

ORDER BY SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID;










