SELECT 
--  PUPILID MA_HS
  SAMS.EDU_SCHOOL.SCHOOLNAME MA_TRUONG
  ,SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME MA_LOP
  ,FULLNAME TEN_HS
  ,TO_CHAR(BIRTHDAY,'DD/MM/YYYY') NGAY_SINH
  ,DECODE(gender,0,'Nam','N?') GIOI_TINH
  ,SAMS.EDU_PUPILSTATUS.PUPILSTATUSNAME TRANG_THAI
  ,'' LY_DO_THOI_HOC
  ,ETHNICITYNAME DAN_TOC
  ,NATIONLATYNAME QUOC_GIA
  ,SAMS.MD_PROVINCE.PROVINCENAME TINH
  ,DISTRICTNAME HUYEN
  ,WARDNAME XA
  ,BIRTHPLACE NOI_SINH
  ,HAMLETNAME XOM
  ,PERMANENTFULLADDRESS DIA_CHI
  ,CONTACTPHONE SDT_LIEN_HE
  ,'' KHU_VUC
  ,'' HINH_THUC_HOC_TAP
  ,SAMS.GETPOLICYOBJECTTYPENAMELIST(SAMS.EDU_PUPIL.PUPILID) DOI_TUONG_CS
  ,SAMS.EDU_PUPIL.IDCARD CMND
  ,IDCARDPROVINCE.PROVINCENAME NOI_CAP
  ,TO_CHAR(SAMS.EDU_PUPIL.IDCARDISSUEDATE,'DD/MM/YYYY') NGAY_CAP
  ,CASE WHEN SAMS.EDU_PUPIL.ismemberofyouthunion = 1 THEN 'x' END LA_DOI_VIEN
  ,CASE WHEN SAMS.EDU_PUPIL.ISMEMBEROFJUNIORYOUTHUNION = 1 THEN 'x' END LA_DOAN_VIEN
  ,'' CO_ME_LA_DAN_TOC
  ,'' CO_CHA_LA_DAN_TOC
  ,SAMS.EDU_PUPIL.ISREPEATCLASS LUU_BAN
  ,SAMS.EDU_PUPIL.FATHERFULLNAME HO_TEN_CHA
  ,CASE WHEN FATHERJOB.ISOTHER = 1 THEN SAMS.EDU_PUPIL.FATHERJOBTITLE ELSE FATHERJOB.JOBNAME END NGHE_NGHIEP_CHA
  ,TO_CHAR(SAMS.EDU_PUPIL.FATHERBIRTHDAY,'YYYY') NAM_SINH_CHA
  ,SAMS.EDU_PUPIL.MOTHERFULLNAME HO_TEN_ME
  ,CASE WHEN MOTHERJOB.ISOTHER = 1 THEN SAMS.EDU_PUPIL.MOTHERJOBTITLE ELSE MOTHERJOB.JOBNAME END NGHE_NGHIEP_ME
  ,TO_CHAR(SAMS.EDU_PUPIL.MOTHERBIRTHDAY,'YYYY') NAM_SINH_ME
    ,SAMS.EDU_PUPIL.GUARDIANFULLNAME HO_TEN_GH
  ,CASE WHEN GUARDIANJOB.ISOTHER = 1 THEN SAMS.EDU_PUPIL.GUARDIANJOBTITLE ELSE GUARDIANJOB.JOBNAME END NGHE_NGHIEP_GH
  ,TO_CHAR(SAMS.EDU_PUPIL.GUARDIANBIRTHDAY,'YYYY') NAM_SINH_GH
  FROM SAMS.EDU_PUPIL_STUDYTIMELINE
  
LEFT JOIN SAMS.EDU_PUPIL
  ON SAMS.EDU_PUPIL.PUPILID = SAMS.EDU_PUPIL_STUDYTIMELINE.PUPILID
LEFT JOIN SAMS.EDU_SCHOOL
  ON SAMS.EDU_SCHOOL.SCHOOLID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLID
LEFT JOIN SAMS.EDU_SCHOOLCLASS_NEW
  ON SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID
LEFT JOIN SAMS.EDU_CLASS
  ON SAMS.EDU_CLASS.CLASSID = SAMS.EDU_SCHOOLCLASS_NEW.CLASSID
LEFT JOIN SAMS.EDU_PUPILSTATUS
  ON SAMS.EDU_PUPILSTATUS.PUPILSTATUSID = SAMS.EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID
LEFT  JOIN SAMS.MD_NATIONLATY
  ON SAMS.MD_NATIONLATY.NATIONLATYID = SAMS.EDU_PUPIL.NATIONLATYID
 LEFT   JOIN SAMS.MD_PROVINCE
  ON SAMS.MD_PROVINCE.PROVINCEID = SAMS.EDU_PUPIL.PERMANENTPROVINCEID
 LEFT   JOIN SAMS.MD_DISTRICT
  ON SAMS.MD_DISTRICT.DISTRICTID = SAMS.EDU_PUPIL.PERMANENTDISTRICTID
 LEFT   JOIN SAMS.MD_WARD
  ON SAMS.MD_WARD.WARDID = SAMS.EDU_PUPIL.PERMANENTWARDID
LEFT  JOIN SAMS.MD_HAMLET
  ON SAMS.MD_HAMLET.HAMLETID = SAMS.EDU_PUPIL.PERMANENTHAMLETID
 LEFT   JOIN SAMS.PL_ETHNICITY
  ON SAMS.PL_ETHNICITY.ETHNICITYID = SAMS.EDU_PUPIL.ETHNICITYID
LEFT JOIN SAMS.MD_PROVINCE IDCARDPROVINCE
  ON SAMS.EDU_PUPIL.idcardissueplaceid = IDCARDPROVINCE.provinceid
LEFT JOIN SAMS.MD_JOB FATHERJOB
  ON FATHERJOB.JOBID = SAMS.EDU_PUPIL.FATHERJOBID
  LEFT JOIN SAMS.MD_JOB MOTHERJOB
  ON MOTHERJOB.JOBID = SAMS.EDU_PUPIL.MOTHERJOBID
  LEFT JOIN SAMS.MD_JOB GUARDIANJOB
  ON GUARDIANJOB.JOBID = SAMS.EDU_PUPIL.GUARDIANJOBID
WHERE 
SAMS.EDU_PUPIL.ISACTIVE = 1
  AND SAMS.EDU_PUPIL.ISDELETED = 0
   AND SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 21
  AND SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 2
  AND SAMS.EDU_SCHOOLCLASS_NEW.isactive = 1
  AND SAMS.EDU_SCHOOLCLASS_NEW.isdeleted = 0
--  AND SAMS.EDU_CLASS.EDUCATIONLEVELID = 7
  AND SAMS.EDU_CLASS.isactive = 1
  AND SAMS.EDU_CLASS.isdeleted = 0

AND edu_school.schoolid NOT IN (
  SELECT schoolid   FROM SAMS.edu_school
  WHERE UPPER(schoolname) LIKE '%TU DO%')
 
    AND edu_school.schoolid NOT IN (1524,1530,10112318,1541,1525,1515,1470,1469,1528)
--  AND edu_school.schoolid NOT IN (
--  SELECT CONFIGVALUE   FROM SAMS.SYS_APPCONFIG
--  WHERE APPCONFIGID = 'RPT_LISTOFNON - STATISTICSSCHOOL')
    AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 21
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 2
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
  AND sams.edu_class.classid = 8
  

ORDER BY SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID;


