SELECT 
  '' STT_QH	
  ,PARENTORGANDISTRICT.DISTRICTNAME QUANHUYEN
  ,'' ISSELECT	
  ,SAMS.EDU_PUPIL.PUPILID ID	
  ,SAMS.EDU_PUPIL.CURRENTSCHOOLID	
  ,EDU_SCHOOL.SCHOOLNAME SCHOOLNAME	
  ,SAMS.EDU_PUPIL.CURRENTCLASSID CLASSID
  ,EDU_CLASS.CLASSNAME CLASSNAME	
  ,EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME SCHOOLCLASSNAME	
  ,SAMS.EDU_PUPIL.FULLNAME	
  ,SAMS.EDU_PUPIL.GENDER	
  ,DECODE(SAMS.EDU_PUPIL.GENDER,0,'Nam','N?') GENDERNAME	
  ,SAMS.EDU_PUPIL.ETHNICITYID	
  ,PL_ETHNICITY.ETHNICITYNAME ETHNICITYNAME
  , (SELECT 
 LISTAGG(CAST(EDU_POLICYOBJECTTYPE.POLICYOBJECTTYPEID AS VARCHAR2(1800))  ,', ') WITHIN GROUP (ORDER BY EDU_POLICYOBJECTTYPE.POLICYOBJECTTYPEID) 

  FROM SAMS.EDU_PUPIL_POLICYOBJECT 
    JOIN SAMS.EDU_POLICYOBJECTTYPE 
      ON EDU_POLICYOBJECTTYPE.POLICYOBJECTTYPEID = EDU_PUPIL_POLICYOBJECT.POLICYOBJECTTYPEID
  WHERE SAMS.EDU_PUPIL_POLICYOBJECT.PUPILID = SAMS.EDU_PUPIL.PUPILID	) POLICYOBJECTTYPEID
    , (SELECT 
 LISTAGG(CAST(EDU_POLICYOBJECTTYPE.POLICYOBJECTTYPENAME AS VARCHAR2(1800))  ,', ') WITHIN GROUP (ORDER BY EDU_POLICYOBJECTTYPE.POLICYOBJECTTYPEID) 

  FROM SAMS.EDU_PUPIL_POLICYOBJECT 
    JOIN SAMS.EDU_POLICYOBJECTTYPE 
      ON EDU_POLICYOBJECTTYPE.POLICYOBJECTTYPEID = EDU_PUPIL_POLICYOBJECT.POLICYOBJECTTYPEID
  WHERE SAMS.EDU_PUPIL_POLICYOBJECT.PUPILID = SAMS.EDU_PUPIL.PUPILID	) POLICYOBJECTTYPENAME
--  ,POLICYOBJECTTYPEID	
--  ,POLICYOBJECTTYPENAME	
  ,BIRTHDAY	
  ,SAMS.EDU_PUPIL.PLACEOFBIRTHPROVINCEID	
  ,PLACEOFBIRTHPROVINCE.PROVINCENAME PLACEOFBIRTHPROVINCENAME	
  ,SAMS.EDU_PUPIL.DISABILITYTYPEID DISABILITYTYPEIDLIST	
  ,SAMS.MD_DISABILITYTYPE.DISABILITYTYPENAME DISABILITYTYPENAMELIST	
  ,SAMS.EDU_PUPIL.PERMANENTPROVINCEID	
  ,MD_PROVINCE_PER.PROVINCENAME PERMANENTPROVINCENAME	
  ,SAMS.EDU_PUPIL.PERMANENTDISTRICTID	
  ,MD_DISTRICT_PER.DISTRICTNAME PERMANENTDISTRICTNAME	
  ,SAMS.EDU_PUPIL.PERMANENTWARDID	
  ,MD_WARD_PER.WARDNAME PERMANENTWARDNAME	
  ,SAMS.EDU_PUPIL.PERMANENTHAMLETID	
  ,MD_HAMLET_PER.HAMLETNAME PERMANENTHAMLETNAME	
  ,SAMS.EDU_PUPIL.VILLAGEID	
  ,MD_VILLAGE_PER.VILLAGENAME PERMANENTVILLAGENAME	
  ,SAMS.EDU_PUPIL.PROVINCEID	
  ,MD_PROVINCE.PROVINCENAME	
  ,SAMS.EDU_PUPIL.DISTRICTID	
  ,MD_DISTRICT.DISTRICTNAME	
  ,SAMS.EDU_PUPIL.WARDID	
  ,MD_WARD.WARDNAME	
  ,SAMS.EDU_PUPIL.HAMLETID	
  ,MD_HAMLET.HAMLETNAME	
  ,MD_VILLAGE.VILLAGENAME	
  ,'' DECLARANTDATE	
  ,'' DECLARANTFULLNAME	
  ,'' DECLARANTPHONEN	
  ,'' RELATIONSHIPTYPEID	
  ,'' RELATIONSHIPTYPENAME	
  ,'' UPDATEDDATE	
  ,PARENTORGAN.ORGANID PHONGID
  ,PARENTORGAN.ORGANNAME TENPHONG
  FROM SAMS.EDU_PUPIL_STUDYTIMELINE
  
LEFT JOIN SAMS.EDU_PUPIL
  ON SAMS.EDU_PUPIL.PUPILID = SAMS.EDU_PUPIL_STUDYTIMELINE.PUPILID
LEFT JOIN SAMS.EDU_SCHOOL
  ON SAMS.EDU_SCHOOL.SCHOOLID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLID
LEFT JOIN SAMS.MD_ORGAN
  ON SAMS.MD_ORGAN.ORGANID = SAMS.EDU_SCHOOL.ORGANID
LEFT JOIN SAMS.MD_ORGAN PARENTORGAN
  ON PARENTORGAN.ORGANID = SAMS.MD_ORGAN.PARENTID
LEFT JOIN SAMS.MD_DISTRICT PARENTORGANDISTRICT
  ON PARENTORGANDISTRICT.DISTRICTID = PARENTORGAN.DISTRICTID
LEFT JOIN SAMS.EDU_SCHOOLCLASS_NEW
  ON SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID = SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID
LEFT JOIN SAMS.EDU_CLASS
  ON SAMS.EDU_CLASS.CLASSID = SAMS.EDU_SCHOOLCLASS_NEW.CLASSID
LEFT JOIN SAMS.EDU_PUPILSTATUS
  ON SAMS.EDU_PUPILSTATUS.PUPILSTATUSID = SAMS.EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID
LEFT  JOIN SAMS.MD_NATIONLATY
  ON SAMS.MD_NATIONLATY.NATIONLATYID = SAMS.EDU_PUPIL.NATIONLATYID
 LEFT   JOIN SAMS.MD_PROVINCE MD_PROVINCE_PER
  ON SAMS.MD_PROVINCE_PER.PROVINCEID = SAMS.EDU_PUPIL.PERMANENTPROVINCEID
 LEFT   JOIN SAMS.MD_DISTRICT MD_DISTRICT_PER
  ON SAMS.MD_DISTRICT_PER.DISTRICTID = SAMS.EDU_PUPIL.PERMANENTDISTRICTID
 LEFT   JOIN SAMS.MD_WARD MD_WARD_PER
  ON SAMS.MD_WARD_PER.WARDID = SAMS.EDU_PUPIL.PERMANENTWARDID
LEFT  JOIN SAMS.MD_HAMLET MD_HAMLET_PER
  ON SAMS.MD_HAMLET_PER.HAMLETID = SAMS.EDU_PUPIL.PERMANENTHAMLETID
  LEFT  JOIN SAMS.MD_VILLAGE MD_VILLAGE_PER
  ON SAMS.MD_VILLAGE_PER.VILLAGEID = SAMS.EDU_PUPIL.VILLAGEID
  LEFT   JOIN SAMS.MD_PROVINCE
  ON SAMS.MD_PROVINCE.PROVINCEID = SAMS.EDU_PUPIL.PROVINCEID
 LEFT   JOIN SAMS.MD_DISTRICT
  ON SAMS.MD_DISTRICT.DISTRICTID = SAMS.EDU_PUPIL.DISTRICTID
 LEFT   JOIN SAMS.MD_WARD
  ON SAMS.MD_WARD.WARDID = SAMS.EDU_PUPIL.WARDID
LEFT  JOIN SAMS.MD_HAMLET
  ON SAMS.MD_HAMLET.HAMLETID = SAMS.EDU_PUPIL.HAMLETID
  LEFT  JOIN SAMS.MD_VILLAGE
  ON SAMS.MD_VILLAGE.VILLAGEID = SAMS.EDU_PUPIL.VILLAGEID
 LEFT   JOIN SAMS.PL_ETHNICITY
  ON SAMS.PL_ETHNICITY.ETHNICITYID = SAMS.EDU_PUPIL.ETHNICITYID
LEFT JOIN SAMS.MD_PROVINCE IDCARDPROVINCE
  ON SAMS.EDU_PUPIL.IDCARDISSUEPLACEID = IDCARDPROVINCE.PROVINCEID
LEFT JOIN SAMS.MD_JOB FATHERJOB
  ON FATHERJOB.JOBID = SAMS.EDU_PUPIL.FATHERJOBID
  LEFT JOIN SAMS.MD_JOB MOTHERJOB
  ON MOTHERJOB.JOBID = SAMS.EDU_PUPIL.MOTHERJOBID
  LEFT JOIN SAMS.MD_JOB GUARDIANJOB
  ON GUARDIANJOB.JOBID = SAMS.EDU_PUPIL.GUARDIANJOBID
  LEFT JOIN SAMS.MD_DISABILITYTYPE
  ON SAMS.EDU_PUPIL.DISABILITYTYPEID = MD_DISABILITYTYPE.DISABILITYTYPEID
  LEFT   JOIN SAMS.MD_PROVINCE PLACEOFBIRTHPROVINCE
  ON SAMS.PLACEOFBIRTHPROVINCE.PROVINCEID = SAMS.EDU_PUPIL.PLACEOFBIRTHPROVINCEID
WHERE 
SAMS.EDU_PUPIL.ISACTIVE = 1
  AND SAMS.EDU_PUPIL.ISDELETED = 0
   AND SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 21
  AND SAMS.EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 2
  AND SAMS.EDU_SCHOOLCLASS_NEW.ISACTIVE = 1
  AND SAMS.EDU_SCHOOLCLASS_NEW.ISDELETED = 0
--  AND SAMS.EDU_CLASS.EDUCATIONLEVELID = 7
  AND SAMS.EDU_CLASS.ISACTIVE = 1
  AND SAMS.EDU_CLASS.ISDELETED = 0

AND EDU_SCHOOL.SCHOOLID NOT IN (
  SELECT SCHOOLID   FROM SAMS.EDU_SCHOOL
  WHERE UPPER(SCHOOLNAME) LIKE '%T? DO%')
 
    AND EDU_SCHOOL.SCHOOLID NOT IN (1524,1530,10112318,1541,1525,1515,1470,1469,1528)
--  AND EDU_SCHOOL.SCHOOLID NOT IN (
--  SELECT CONFIGVALUE   FROM SAMS.SYS_APPCONFIG
--  WHERE APPCONFIGID = 'RPT_LISTOFNON - STATISTICSSCHOOL')
    AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 21
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 2
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
  AND SAMS.EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
  AND SAMS.EDU_CLASS.CLASSID IN (8)
  
--AND SAMS.EDU_PUPIL.PUPILID = '015906775'
ORDER BY parentorgan.orderindex,edu_school.orderindex,edu_class.orderindex, SAMS.EDU_SCHOOLCLASS_NEW.orderindex;


