SELECT 
  to_char(pupilid) MA_HS,
  to_char(identificationnumber) SBD,
  Substr(lastname, 1, Instr(lastname, ' ') - 1) AS HO,
  Substr(lastname, Instr(lastname, ' ') + 1)    AS DEM,
 firstname AS TEN,
   birthday,
  GENDERNAME,
  PLACEOFBIRTHFULLNAME,
  ETHNICITYNAME, --Dân t?c Name
  THCS,
  districtname,
 schoolclassname,
  MaTHPT,
  schoolid,
  schoolname,
-- NOTE
  SCHOOLNAMELIENKET
       FROM
  (

SELECT DISTINCT 
  edu_g10examresult.pupilid,
  edu_pupil.firstname,
  edu_pupil.lastname,
  edu_pupil.fullname,
  to_char(edu_pupil.birthday,'DD/MM/YYYY') birthday,
  DECODE(GENDER, 0,N'Nam', N'N?') GENDERNAME,
  NVL(MD_PROVINCE.PROVINCENAME, MD_COUNTRY.COUNTRYNAME) PLACEOFBIRTHFULLNAME,
  PL_ETHNICITY.ETHNICITYNAME, --Dân t?c Name
  SCHOOLTHCS.SCHOOLNAME THCS,
  MDTHCS.DISTRICTNAME,
  ESN.SCHOOLCLASSNAME,
  EDU_SCHOOL.SCHOOLID MATHPT,
  EDU_SCHOOL.SCHOOLID,
  EDU_SCHOOL.SCHOOLNAME,
  
  IDENTIFICATIONNUMBER, 
--  es1.educationtypename
--  CASE WHEN eps.linkschoolid IS NOT NULL THEN N'H?c sinh liên k?t' ELSE N'H?c sinh c?a tru?ng' END NOTE
  LK.SCHOOLNAME SCHOOLNAMELIENKET
  FROM SAMS.EDU_G10EXAMRESULT
  LEFT JOIN SAMS.EDU_PUPIL_G10EXAMRESULT
  ON SAMS.EDU_PUPIL_G10EXAMRESULT.PUPILID = SAMS.EDU_G10EXAMRESULT.PUPILID
  AND EDU_PUPIL_G10EXAMRESULT.SCHOOLYEARID = 2
  AND EDU_PUPIL_G10EXAMRESULT.ISDELETED = 0
  LEFT JOIN SAMS.EDU_PUPIL
  ON SAMS.EDU_PUPIL.PUPILID = SAMS.EDU_G10EXAMRESULT.PUPILID
  JOIN SAMS.EDU_PUPIL_STUDYTIMELINE EPS
  ON EDU_PUPIL.PUPILID = EPS.PUPILID
  AND EPS.SCHOOLYEARID = 21 AND EPS.SCHOOLTERMID = 1
  AND EPS.ISACTIVE = 1 AND EPS.ISDELETED = 0
--  AND EPS.CURRENTPUPILSTATUSID = 1
  LEFT JOIN SAMS.PL_ETHNICITY ON  EDU_PUPIL.ETHNICITYID = PL_ETHNICITY.ETHNICITYID
  LEFT JOIN SAMS.MD_COUNTRY ON  EDU_PUPIL.PLACEOFBIRTHCOUNTRYID = MD_COUNTRY.COUNTRYID
  LEFT JOIN SAMS.MD_PROVINCE ON EDU_PUPIL.PLACEOFBIRTHPROVINCEID = MD_PROVINCE.PROVINCEID
  LEFT JOIN SAMS.EDU_SCHOOL SCHOOLTHCS
  ON SCHOOLTHCS.SCHOOLID = EDU_G10EXAMRESULT.JUNIORSCHOOLID
  LEFT JOIN SAMS.MD_ORGAN MO
  ON MO.ORGANID = SCHOOLTHCS.ORGANID
  LEFT JOIN SAMS.MD_DISTRICT MDTHCS
  ON MO.DISTRICTID = MDTHCS.DISTRICTID
  LEFT JOIN SAMS.EDU_SCHOOLCLASS_NEW ESN
  ON ESN.SCHOOLCLASSID = EDU_G10EXAMRESULT.JUNIORSCHOOLCLASSID
  AND ESN.SCHOOLYEARID = EDU_G10EXAMRESULT.SCHOOLYEARID
  AND ESN.SCHOOLTERMID = 2 
  LEFT JOIN SAMS.EDU_SCHOOL
  ON SAMS.EDU_SCHOOL.SCHOOLID = EDU_G10EXAMRESULT.HISCHOOLID  
  JOIN SAMS.EDU_SCHOOL_EDUCATIONLEVEL ESE
  ON ESE.SCHOOLID = EDU_G10EXAMRESULT.HISCHOOLID  
  LEFT JOIN SAMS.EDU_EDUCATIONTYPE  ES1
  ON EDU_SCHOOL.EDUCATIONTYPEID = ES1.EDUCATIONTYPEID
 AND ES1.ISACTIVE = 1 
 AND ES1.ISDELETED = 0
--    LEFT JOIN 
--  (
--    SELECT eps1.pupilid, es.schoolname, eps1.schoolid,eps1.linkschoolid
--      FROM sams.edu_pupil_studytimeline EPS1
--      JOIN sams.edu_school es
--        ON es.schoolid = eps1.schoolid
--        AND es.isactive = 1 AND es.isdeleted = 0
--      WHERE eps1.schoolyearid = 21 AND eps1.isactive = 1 AND eps1.isdeleted = 0 AND eps1.schooltermid = 1
--  ) LK
--  ON EDU_PUPIL_G10EXAMRESULT.pupilid = lk.pupilid
--  AND eps.schoolid = lk.linkschoolid
 LEFT  JOIN SAMS.EDU_PUPIL_STUDYTIMELINE EPS1
  ON EDU_PUPIL.PUPILID = EPS1.PUPILID
  AND EPS.schoolid = EPS1.schoolid
  AND eps.linkschoolid IS NOT NULL
  AND EPS1.SCHOOLYEARID = 21 AND EPS1.SCHOOLTERMID = 1
  AND EPS1.ISACTIVE = 1 AND EPS1.ISDELETED = 0
  LEFT JOIN sams.edu_school lk
  ON lk.schoolid = eps1.schoolid
  
  WHERE 
  SAMS.EDU_PUPIL.ISACTIVE = 1
  AND SAMS.EDU_PUPIL.ISDELETED = 0 
  AND SAMS.EDU_SCHOOL.ISACTIVE = 1
  AND SAMS.EDU_SCHOOL.ISDELETED = 0 
  AND ESE.EDUCATIONLEVELID = 7
  AND 
  SAMS.EDU_G10EXAMRESULT.ISDELETED = 0 
  AND SAMS.EDU_G10EXAMRESULT.SCHOOLYEARID = 21
  
 AND EDU_SCHOOL.SCHOOLID NOT IN   (1592,1593,1594,1595,1596,1597,1598,1599,1600,1605,1607,1610,1618,1613,1614,1616,1608
                                    ,1611,1615,1602,1603,1604,1609,1617,1601,1606,1612,1524,1530,10112318,1525,1515,1470,1528,1469)
--  AND UPPER(SAMS.EDU_SCHOOL.SCHOOLNAME) NOT LIKE '%T? DO%'
--  AND SAMS.EDU_G10EXAMRESULT.PUPILID = '011103314'

  )
  ORDER BY SCHOOLNAME
