SELECT    DISTINCT
--                  EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID,
--                  NVL(EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME, EDU_PUPIL.DESCRIPTION) CURRENTSCHOOLCLASSNAME,
                  EDU_PUPIL.PUPILID,                
                  EDU_PUPIL.LASTNAME , 
                  EDU_PUPIL.FIRSTNAME,   
                  DECODE(EDU_PUPIL.GENDER, 0 , 'Nam', 'Nữ') GENDERNAME,                  
                  TO_CHAR(EDU_PUPIL.BIRTHDAY, 'MM/DD/YYYY') BIRTHDAY,      
--                   EDU_PUPIL.ETHNICITYID,
--                  PL_ETHNICITY.ETHNICITYNAME,            
                  CASE
                    WHEN PLACEOFBIRTHCOUNTRYID = 250 THEN
                      PLACEOFBIRTHROVINCE.PROVINCENAME
                    ELSE
                      PLACEOFBIRTHCOUNTRY.COUNTRYNAME
                  END PLACEOFBIRTHFULL,
--                  CASE
--                    WHEN BIRTHCOUNTRYID = 250 THEN
--                      BIRTHPROVINCE.PROVINCENAME
--                    ELSE   BIRTHCOUNTRY.COUNTRYNAME
--                  END BIRTHPLACE,
--                  PERMANENTPROVINCEPUPIL.PROVINCENAME PERMANENTPROVINCEPUPIL,
--                  DISTRICTPUPIL.DISTRICTNAME DISTRICTNAMEPUPIL,
--                  WARDPUPIL.WARDNAME WARDNAMEPUPIL,
--                  HAMLETPUPIL.HAMLETNAME HAMLETNAMEPUPIL,
--                  PERMANENTDISTRICTPUPIL.DISTRICTNAME PERMANENTDISTRICTNAMEPUPIL,
--                  PERMANENTWARDPUPIL.WARDNAME PERMANENTWARDNAMEPUPIL,
--                  PERMANENTHAMLETPUPIL.HAMLETNAME PERMANENTHAMLETNAMEPUPIL,
--                  PERMANENTVILLAGEPUPIL.VILLAGENAME PERMANENTVILLAGENAMEPUPIL,
                  LTRIM((NVL2( EDU_PUPIL.PERMANENTADDRESS,  EDU_PUPIL.PERMANENTADDRESS, '')
                  || NVL2(PERMANENTVILLAGEPUPIL.VILLAGENAME, ', ' || PERMANENTVILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(PERMANENTHAMLETPUPIL.HAMLETNAME, ', ' || PERMANENTHAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(PERMANENTWARDPUPIL.WARDNAME, ', ' || PERMANENTWARDPUPIL.WARDNAME, '')
                  || NVL2(PERMANENTDISTRICTPUPIL.DISTRICTNAME, ', ' || PERMANENTDISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PERMANENTPROVINCEPUPIL.PROVINCENAME, ', ' || PERMANENTPROVINCEPUPIL.PROVINCENAME, '')), ',')PERMANENTFULLADDRESS,
--                  PROVINCEPUPIL.PROVINCENAME,
--                  DISTRICTPUPIL.DISTRICTNAME,
--                  WARDPUPIL.WARDNAME,
--                  VILLAGEPUPIL.VILLAGENAME,
--                  HAMLETPUPIL.HAMLETNAME,
                  LTRIM((NVL2(EDU_PUPIL.ADDRESS, EDU_PUPIL.ADDRESS, '')
                  || NVL2(VILLAGEPUPIL.VILLAGENAME, ', ' || VILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(HAMLETPUPIL.HAMLETNAME, ', ' || HAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(WARDPUPIL.WARDNAME, ', ' || WARDPUPIL.WARDNAME, '')
                  || NVL2(DISTRICTPUPIL.DISTRICTNAME, ', ' || DISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PROVINCEPUPIL.PROVINCENAME, ', ' || PROVINCEPUPIL.PROVINCENAME, '')), ',') FULLADDRESS,  
                  PL_ETHNICITY.ETHNICITYNAME
                  ,CASE WHEN EDU_PUPIL_POLICYOBJECT.POLICYOBJECTTYPEID = 3  THEN 'X' ELSE ' ' END CONLIETSI
                  ,CASE WHEN EDU_PUPIL_POLICYOBJECT.POLICYOBJECTTYPEID = 5  THEN 'X' ELSE ' ' END CONTBHANG
                  ,''GDCOCONGCM
                  ,CASE WHEN EDU_PUPIL.ISDISABILITYPUPIL = 1  THEN 'X' ELSE ' ' END KHUYET_TAT
                  ,EDU_PUPIL_STUDYTIMELINE.SCHOOLID,   
                  NVL(EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME, EDU_PUPIL.DESCRIPTION) CURRENTSCHOOLCLASSNAME 
                  ,'' hoc_luc
                  ,'' hanh_kiem
                  ,'' DTBCN
                  ,'' DIEM_KK
                  ,'' DIEN_UT
                  ,EDU_SUBJECTSECTION.SUBJECTSECTIONNAME PHANBAN 
                  ,'' NGOAINGU
                  ,'' NV1
                  ,'' NV2
                  ,'' KHUVUC
                  ,NVL(EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME, EDU_PUPIL.DESCRIPTION)   LOP9
                  ,'' DTBMCNTO9
                  ,'' DTBMCNLY9
                  ,'' DTBMCNHO9
                  ,'' DTBMCNSI9
                  ,'' DTBMCNTI9
                  ,'' DTBMCNVA9
                  ,'' DTBMCNSU9
                  ,'' DTBMCNDI9
                  ,'' DTBMCNNN9
                  ,'' DTBMCNGD9
                  ,'' DTBMCNCN9
                  ,'' DTBMCNTD9
                  ,'' DTBMCNMT9
                  ,'' DTBMCNAM9
                  ,'' DTBMCNMC9
                  ,'' DTBMCNCD9
                  ,'' DTBMCNCX9
                  ,'' DTBHK19
                  ,'' HOC_LUC19
                  ,'' H_KIEM19
                  ,'' P_LOAI19
                  ,'' DTBHK29
                  ,'' HOC_LUC29
                  ,'' H_KIEM29
                  ,'' P_LOAI29
                  ,'' DTBCN9
                  ,'' HOC_LUC9
                  ,'' HANHKIEM9
                  ,'' PHANLOAI9
                  ,'' LUUBAN9              

                  ,EDU_PUPIL.FATHERFULLNAME,
--                  TO_CHAR(EDU_PUPIL.FATHERBIRTHDAY, 'MM/DD/YYYY') FATHERBIRTHDAY,
--                  NVL2(MJF.JOBNAME, CASE WHEN MJF.ISOTHER = 1 THEN FATHERJOBTITLE ELSE MJF.JOBNAME END, FATHERJOBTITLE) FATHERJOBNAME,
                  EDU_PUPIL.MOTHERFULLNAME,
                  EDU_PUPIL.CONTACTPHONE
--                  TO_CHAR(EDU_PUPIL.MOTHERBIRTHDAY, 'MM/DD/YYYY') MOTHERBIRTHDAY,
--                  NVL2(MJM.JOBNAME, CASE WHEN MJM.ISOTHER = 1 THEN MOTHERJOBTITLE ELSE MJM.JOBNAME END, MOTHERJOBTITLE) MOTHERJOBNAME,
                  
--                  EDU_PUPIL.GUARDIANFULLNAME,
--                 TO_CHAR(EDU_PUPIL.guardianbirthday,'MM/DD/YYYY') GUARDIANBIRTHDAY
                        

        FROM      SAMS.EDU_PUPIL
        JOIN      
            (
              SELECT DISTINCT
                  PUPILID
                  ,SCHOOLID
--                  ,MOVETOSCHOOLID
--                  ,SCHOOLCLASSID
--              
                FROM sams.EDU_PUPIL_STUDYTIMELINE
                WHERE SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 21 -- param: năm học
                                AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 1
                                AND EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
                                AND EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
                                AND EDU_PUPIL_STUDYTIMELINE.currentpupilstatusid = 1
                
             ) EDU_PUPIL_STUDYTIMELINE
  
   
          ON      EDU_PUPIL_STUDYTIMELINE.PUPILID =  EDU_PUPIL.PUPILID
          AND     edu_pupil_studytimeline.schoolid =   EDU_PUPIL.currentschoolid
        LEFT
        JOIN      SAMS.EDU_SCHOOL
          ON      EDU_SCHOOL.SCHOOLID = EDU_PUPIL_STUDYTIMELINE.SCHOOLID
         
        LEFT
        JOIN      SAMS.MD_DISTRICT SCHOOLDISTRICT
          ON      EDU_SCHOOL.DISTRICTID = SCHOOLDISTRICT.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD SCHOOLWARD
          ON      EDU_SCHOOL.WARDID = SCHOOLWARD.WARDID
        LEFT
        JOIN      SAMS.EDU_SCHOOLCLASS_NEW
                ON      EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID = EDU_PUPIL.currentschoolclassid
                AND     EDU_SCHOOLCLASS_NEW.ISACTIVE = 1 AND EDU_SCHOOLCLASS_NEW.ISDELETED = 0
                AND EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 21 -- param: năm học
                AND EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 1
        LEFT JOIN SAMS.EDU_SUBJECTSECTION
          ON    EDU_SUBJECTSECTION.SUBJECTSECTIONID = EDU_SCHOOLCLASS_NEW.SUBJECTSECTIONID
          AND   EDU_SUBJECTSECTION.ISDELETED = 0 AND EDU_SUBJECTSECTION.ISACTIVE = 1  
             
        
        LEFT
        JOIN      SAMS.EDU_CLASS
          ON      EDU_CLASS.CLASSID = EDU_SCHOOLCLASS_NEW.CLASSID
          AND     EDU_CLASS.ISACTIVE = 1 AND EDU_CLASS.ISDELETED = 0
        LEFT
        JOIN      SAMS.EDU_CLASS EDU_CLASS_PUPIL
          ON      EDU_CLASS_PUPIL.CLASSID = EDU_PUPIL.CURRENTCLASSID
        LEFT
        JOIN      SAMS.EDU_EDUCATIONLEVEL
          ON      EDU_CLASS.EDUCATIONLEVELID =EDU_EDUCATIONLEVEL.EDUCATIONLEVELID

        LEFT
        JOIN      SAMS.SYS_USER PUPILCREATEUSER
          ON      PUPILCREATEUSER.USERNAME = EDU_PUPIL.CREATEDUSER
        LEFT
        JOIN      SAMS.SYS_USER PUPILUPDATEDUSER
          ON      PUPILUPDATEDUSER.USERNAME = EDU_PUPIL.UPDATEDUSER
        LEFT
        JOIN      SAMS.SYS_USER PUPILDELETEDUSER
          ON      PUPILDELETEDUSER.USERNAME = EDU_PUPIL.DELETEDUSER
        LEFT
        JOIN      SAMS.MD_PROVINCE PERMANENTPROVINCEPUPIL
          ON      EDU_PUPIL.PERMANENTPROVINCEID = PERMANENTPROVINCEPUPIL.PROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT PERMANENTDISTRICTPUPIL
          ON      EDU_PUPIL.PERMANENTDISTRICTID = PERMANENTDISTRICTPUPIL.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD PERMANENTWARDPUPIL
          ON      EDU_PUPIL.PERMANENTWARDID = PERMANENTWARDPUPIL.WARDID
        LEFT
        JOIN      SAMS.MD_HAMLET PERMANENTHAMLETPUPIL
          ON      EDU_PUPIL.PERMANENTHAMLETID = PERMANENTHAMLETPUPIL.HAMLETID
        LEFT
        JOIN      SAMS.MD_VILLAGE PERMANENTVILLAGEPUPIL
          ON      EDU_PUPIL.PERMANENTVILLAGEID = PERMANENTVILLAGEPUPIL.VILLAGEID
        LEFT
        JOIN      SAMS.MD_PROVINCE PROVINCEPUPIL
          ON      EDU_PUPIL.PROVINCEID = PROVINCEPUPIL.PROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT DISTRICTPUPIL
          ON      EDU_PUPIL.DISTRICTID = DISTRICTPUPIL.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD WARDPUPIL
          ON      EDU_PUPIL.WARDID = WARDPUPIL.WARDID
        LEFT
        JOIN      SAMS.MD_HAMLET HAMLETPUPIL
          ON      EDU_PUPIL.HAMLETID = HAMLETPUPIL.HAMLETID
        LEFT
        JOIN      SAMS.MD_VILLAGE VILLAGEPUPIL
          ON      EDU_PUPIL.VILLAGEID = VILLAGEPUPIL.VILLAGEID
        LEFT
        JOIN      SAMS.MD_JOB MJF
          ON      MJF.JOBID = EDU_PUPIL.FATHERJOBID
        LEFT
        JOIN      SAMS.MD_JOB MJM
          ON      MJM.JOBID = EDU_PUPIL.MOTHERJOBID
        LEFT
        JOIN      SAMS.PL_ETHNICITY
          ON      EDU_PUPIL.ETHNICITYID = PL_ETHNICITY.ETHNICITYID
        LEFT
        JOIN      SAMS.MD_COUNTRY BIRTHCOUNTRY
          ON      BIRTHCOUNTRY.COUNTRYID = EDU_PUPIL.BIRTHCOUNTRYID
        LEFT
        JOIN      SAMS.MD_PROVINCE BIRTHPROVINCE
          ON      BIRTHPROVINCE.PROVINCEID = EDU_PUPIL.BIRTHPROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT BIRTHDISTRICT
          ON      BIRTHDISTRICT.DISTRICTID = EDU_PUPIL.BIRTHDISTRICTID
        LEFT
        JOIN      SAMS.MD_COUNTRY PLACEOFBIRTHCOUNTRY
          ON      PLACEOFBIRTHCOUNTRY.COUNTRYID = EDU_PUPIL.PLACEOFBIRTHCOUNTRYID
        LEFT
        JOIN      SAMS.MD_PROVINCE PLACEOFBIRTHROVINCE
          ON      PLACEOFBIRTHROVINCE.PROVINCEID = EDU_PUPIL.PLACEOFBIRTHPROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT PLACEOFBIRTHDISTRICT
          ON      PLACEOFBIRTHDISTRICT.DISTRICTID = EDU_PUPIL.PLACEOFBIRTHDISTRICTID

       LEFT JOIN
        (
          SELECT  edu_pupil_policyobject.pupilid,EDU_PUPIL_POLICYOBJECT.policyobjecttypeid
            FROM  SAMS.EDU_PUPIL_POLICYOBJECT
            JOIN SAMS.edu_policyobjecttype 
            ON edu_policyobjecttype.policyobjecttypeid = EDU_PUPIL_POLICYOBJECT.policyobjecttypeid
            AND edu_policyobjecttype.isactive = 1 AND edu_policyobjecttype.isdeleted = 0
            GROUP BY edu_pupil_policyobject.pupilid,EDU_PUPIL_POLICYOBJECT.policyobjecttypeid
         )EDU_PUPIL_POLICYOBJECT
 
          ON EDU_PUPIL.pupilid = EDU_PUPIL_POLICYOBJECT.PUPILID 

        WHERE     EDU_PUPIL.ISDELETED = 0
        AND EDU_PUPIL.isactive = 1 
        AND edu_pupil.currentclassid IN (12,22)
        AND edu_pupil.currentpupilstatusid = 1
        AND edu_pupil.currentschoolid NOT IN (1592,1593,1594,1595,1596,1597,1598,1599,1600,1605,1607,1610,1618,1613,1614,1616,1608,1611,1615,1602,1603,1604,1609,1617,1601,1606,1612,1524,1530,10112318,1525,1515,1470,1528,1469) 
 
 ORDER BY
                edu_pupil_studytimeline.schoolid,
                
                FIRSTNAME,
                LASTNAME,
                BIRTHDAY,
                NLSSORT(NLS_LOWER(FIRSTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                NLSSORT(NLS_LOWER(LASTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                BIRTHDAY;