SELECT    
                  EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID,
                  NVL(EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME, EDU_PUPIL.DESCRIPTION) CURRENTSCHOOLCLASSNAME,
                  EDU_PUPIL.PUPILID,
                  EDU_PUPIL.FULLNAME,  
                  EDU_PUPIL.FIRSTNAME,
                  EDU_PUPIL.LASTNAME ,    
                  DECODE(EDU_PUPIL.GENDER, 0 , 'Nam', 'N?') GENDERNAME,
                  
                  TO_CHAR(EDU_PUPIL.BIRTHDAY, 'MM/DD/YYYY') BIRTHDAY,      
--                   EDU_PUPIL.ETHNICITYID,
                  PL_ETHNICITY.ETHNICITYNAME,            
                  CASE
                    WHEN PLACEOFBIRTHCOUNTRYID = 250 THEN
                      PLACEOFBIRTHROVINCE.PROVINCENAME
                    ELSE
                      PLACEOFBIRTHCOUNTRY.COUNTRYNAME
                  END PLACEOFBIRTHFULL,
                  CASE
                    WHEN BIRTHCOUNTRYID = 250 THEN
                      BIRTHPROVINCE.PROVINCENAME
                    ELSE   BIRTHCOUNTRY.COUNTRYNAME
                  END BIRTHPLACE,
                  PERMANENTPROVINCEPUPIL.PROVINCENAME PERMANENTPROVINCEPUPIL,
                  DISTRICTPUPIL.DISTRICTNAME DISTRICTNAMEPUPIL,
                  WARDPUPIL.WARDNAME WARDNAMEPUPIL,
                  HAMLETPUPIL.HAMLETNAME HAMLETNAMEPUPIL,
                  PERMANENTDISTRICTPUPIL.DISTRICTNAME PERMANENTDISTRICTNAMEPUPIL,
                  PERMANENTWARDPUPIL.WARDNAME PERMANENTWARDNAMEPUPIL,
                  PERMANENTHAMLETPUPIL.HAMLETNAME PERMANENTHAMLETNAMEPUPIL,
                  PERMANENTVILLAGEPUPIL.VILLAGENAME PERMANENTVILLAGENAMEPUPIL,
                  LTRIM((NVL2( EDU_PUPIL.PERMANENTADDRESS,  EDU_PUPIL.PERMANENTADDRESS, '')
                  || NVL2(PERMANENTVILLAGEPUPIL.VILLAGENAME, ', ' || PERMANENTVILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(PERMANENTHAMLETPUPIL.HAMLETNAME, ', ' || PERMANENTHAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(PERMANENTWARDPUPIL.WARDNAME, ', ' || PERMANENTWARDPUPIL.WARDNAME, '')
                  || NVL2(PERMANENTDISTRICTPUPIL.DISTRICTNAME, ', ' || PERMANENTDISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PERMANENTPROVINCEPUPIL.PROVINCENAME, ', ' || PERMANENTPROVINCEPUPIL.PROVINCENAME, '')), ',')PERMANENTFULLADDRESS,
                  PROVINCEPUPIL.PROVINCENAME,
                  DISTRICTPUPIL.DISTRICTNAME,
                  WARDPUPIL.WARDNAME,
                  VILLAGEPUPIL.VILLAGENAME,
                  HAMLETPUPIL.HAMLETNAME,
                  LTRIM((NVL2(EDU_PUPIL.ADDRESS, EDU_PUPIL.ADDRESS, '')
                  || NVL2(VILLAGEPUPIL.VILLAGENAME, ', ' || VILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(HAMLETPUPIL.HAMLETNAME, ', ' || HAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(WARDPUPIL.WARDNAME, ', ' || WARDPUPIL.WARDNAME, '')
                  || NVL2(DISTRICTPUPIL.DISTRICTNAME, ', ' || DISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PROVINCEPUPIL.PROVINCENAME, ', ' || PROVINCEPUPIL.PROVINCENAME, '')), ',') FULLADDRESS,  
                  EDU_PUPIL.CONTACTPHONE,         
                  EDU_PUPIL.FATHERFULLNAME,
                  TO_CHAR(EDU_PUPIL.FATHERBIRTHDAY, 'MM/DD/YYYY') FATHERBIRTHDAY,
                  NVL2(MJF.JOBNAME, CASE WHEN MJF.ISOTHER = 1 THEN FATHERJOBTITLE ELSE MJF.JOBNAME END, FATHERJOBTITLE) FATHERJOBNAME,
                  EDU_PUPIL.MOTHERFULLNAME,
                  TO_CHAR(EDU_PUPIL.MOTHERBIRTHDAY, 'MM/DD/YYYY') MOTHERBIRTHDAY,
                  NVL2(MJM.JOBNAME, CASE WHEN MJM.ISOTHER = 1 THEN MOTHERJOBTITLE ELSE MJM.JOBNAME END, MOTHERJOBTITLE) MOTHERJOBNAME,
                  
                  EDU_PUPIL.GUARDIANFULLNAME,
                 TO_CHAR(EDU_PUPIL.guardianbirthday,'MM/DD/YYYY') GUARDIANBIRTHDAY
                        

        FROM      SAMS.EDU_PUPIL
        JOIN      
            (
              SELECT 
                  PUPILID
                  ,SCHOOLID
                  ,MOVETOSCHOOLID
                  ,SCHOOLCLASSID
                  ,CURRENTPUPILSTATUSID
                  --,ORDERINDEX
                  ,STARTSTUDYDATE
                  ,ENDSTUDYDATE
                FROM sams.EDU_PUPIL_STUDYTIMELINE
                WHERE SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 21
                                AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 1
                                AND EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
                                AND EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
                        
                        AND     (EDU_PUPIL_STUDYTIMELINE.SCHOOLID = 14030115)
             ) EDU_PUPIL_STUDYTIMELINE
  
   
          ON      EDU_PUPIL_STUDYTIMELINE.PUPILID =  SAMS.EDU_PUPIL.PUPILID

        LEFT
        JOIN      SAMS.EDU_SCHOOL
          ON      EDU_SCHOOL.SCHOOLID = EDU_PUPIL_STUDYTIMELINE.SCHOOLID

        LEFT
        JOIN      SAMS.EDU_SCHOOL EDU_SCHOOLMOVE
          ON      EDU_SCHOOLMOVE.SCHOOLID = EDU_PUPIL_STUDYTIMELINE.MOVETOSCHOOLID

        LEFT
        JOIN      SAMS.md_disabilitytype ON EDU_PUPIL.disabilitytypeid = md_disabilitytype.disabilitytypeid


        LEFT
        JOIN      SAMS.MD_DISTRICT SCHOOLDISTRICT
          ON      EDU_SCHOOL.DISTRICTID = SCHOOLDISTRICT.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD SCHOOLWARD
          ON      EDU_SCHOOL.WARDID = SCHOOLWARD.WARDID
        LEFT
        JOIN      SAMS.EDU_SCHOOLCLASS_NEW
                ON      EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID = EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID
                AND     EDU_SCHOOLCLASS_NEW.ISACTIVE = 1 AND EDU_SCHOOLCLASS_NEW.ISDELETED = 0
                AND EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 21
                AND EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 1
        LEFT
        JOIN      SAMS.EDU_CLASS
          ON      EDU_CLASS.CLASSID = EDU_SCHOOLCLASS_NEW.CLASSID
          AND     EDU_CLASS.ISACTIVE = 1 AND EDU_CLASS.ISDELETED = 0
        LEFT
        JOIN      SAMS.EDU_CLASS EDU_CLASS_PUPIL
          ON      EDU_CLASS_PUPIL.CLASSID = EDU_PUPIL.CURRENTCLASSID
        LEFT
        JOIN      SAMS.EDU_EDUCATIONLEVEL
          ON      EDU_CLASS.EDUCATIONLEVELID =EDU_EDUCATIONLEVEL.EDUCATIONLEVELID

        LEFT
        JOIN      SAMS.SYS_USER PUPILCREATEUSER
          ON      PUPILCREATEUSER.USERNAME = EDU_PUPIL.CREATEDUSER
        LEFT
        JOIN      SAMS.SYS_USER PUPILUPDATEDUSER
          ON      PUPILUPDATEDUSER.USERNAME = EDU_PUPIL.UPDATEDUSER
        LEFT
        JOIN      SAMS.SYS_USER PUPILDELETEDUSER
          ON      PUPILDELETEDUSER.USERNAME = EDU_PUPIL.DELETEDUSER
        LEFT
        JOIN      SAMS.MD_PROVINCE PERMANENTPROVINCEPUPIL
          ON      EDU_PUPIL.PERMANENTPROVINCEID = PERMANENTPROVINCEPUPIL.PROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT PERMANENTDISTRICTPUPIL
          ON      EDU_PUPIL.PERMANENTDISTRICTID = PERMANENTDISTRICTPUPIL.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD PERMANENTWARDPUPIL
          ON      EDU_PUPIL.PERMANENTWARDID = PERMANENTWARDPUPIL.WARDID
        LEFT
        JOIN      SAMS.MD_HAMLET PERMANENTHAMLETPUPIL
          ON      EDU_PUPIL.PERMANENTHAMLETID = PERMANENTHAMLETPUPIL.HAMLETID
        LEFT
        JOIN      SAMS.MD_VILLAGE PERMANENTVILLAGEPUPIL
          ON      EDU_PUPIL.PERMANENTVILLAGEID = PERMANENTVILLAGEPUPIL.VILLAGEID
        LEFT
        JOIN      SAMS.MD_PROVINCE PROVINCEPUPIL
          ON      EDU_PUPIL.PROVINCEID = PROVINCEPUPIL.PROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT DISTRICTPUPIL
          ON      EDU_PUPIL.DISTRICTID = DISTRICTPUPIL.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD WARDPUPIL
          ON      EDU_PUPIL.WARDID = WARDPUPIL.WARDID
        LEFT
        JOIN      SAMS.MD_HAMLET HAMLETPUPIL
          ON      EDU_PUPIL.HAMLETID = HAMLETPUPIL.HAMLETID
        LEFT
        JOIN      SAMS.MD_VILLAGE VILLAGEPUPIL
          ON      EDU_PUPIL.VILLAGEID = VILLAGEPUPIL.VILLAGEID
        LEFT
        JOIN      SAMS.MD_JOB MJF
          ON      MJF.JOBID = EDU_PUPIL.FATHERJOBID
        LEFT
        JOIN      SAMS.MD_JOB MJM
          ON      MJM.JOBID = EDU_PUPIL.MOTHERJOBID
        LEFT
        JOIN      SAMS.PL_ETHNICITY
          ON      EDU_PUPIL.ETHNICITYID = PL_ETHNICITY.ETHNICITYID
        LEFT
        JOIN      SAMS.MD_COUNTRY BIRTHCOUNTRY
          ON      BIRTHCOUNTRY.COUNTRYID = EDU_PUPIL.BIRTHCOUNTRYID
        LEFT
        JOIN      SAMS.MD_PROVINCE BIRTHPROVINCE
          ON      BIRTHPROVINCE.PROVINCEID = EDU_PUPIL.BIRTHPROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT BIRTHDISTRICT
          ON      BIRTHDISTRICT.DISTRICTID = EDU_PUPIL.BIRTHDISTRICTID
        LEFT
        JOIN      SAMS.MD_COUNTRY PLACEOFBIRTHCOUNTRY
          ON      PLACEOFBIRTHCOUNTRY.COUNTRYID = EDU_PUPIL.PLACEOFBIRTHCOUNTRYID
        LEFT
        JOIN      SAMS.MD_PROVINCE PLACEOFBIRTHROVINCE
          ON      PLACEOFBIRTHROVINCE.PROVINCEID = EDU_PUPIL.PLACEOFBIRTHPROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT PLACEOFBIRTHDISTRICT
          ON      PLACEOFBIRTHDISTRICT.DISTRICTID = EDU_PUPIL.PLACEOFBIRTHDISTRICTID

        WHERE     EDU_PUPIL.ISDELETED = 0
          AND     EDU_PUPIL.ISDEMODATA = 0
--          AND     (T_PUPILSTATUSID IS NULL OR (EXISTS (SELECT 1 FROM TMP_IDNUMBER2 WHERE TMP_IDNUMBER2.IDNUMBER = EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID)))
          AND     (-1 <= 0 OR (EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID < 1 AND EDU_PUPIL.CURRENTCLASSID = -1)
                                  OR EDU_SCHOOLCLASS_NEW.CLASSID = -1)

          AND     (
                    (EXISTS (SELECT 1 FROM SAMS.TMP_IDNUMBER TI WHERE EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID = TI.IDNUMBER))
                    OR
                    (-1 <=0 AND 1 > 0)
                  )
--          AND     (
--                    (0 = 0 AND ('' IS NULL OR UPPER(EDU_PUPIL.FULLNAME) LIKE '%' || UPPER('') || '%'
--                    OR ((1 = 1) AND (LENGTH('') <= 20 AND EDU_PUPIL.PUPILID = CAST('' AS CHAR(20 BYTE))))
--                    OR ((1 = 1) AND (LENGTH(T_KEYWORDS) <= 20 AND EDU_PUPIL.IDCARD = CAST('' AS CHAR(20 BYTE))))
--                    ))
--                    OR( 1 = 1 AND ( '' IS NULL OR EDU_PUPIL.PUPILID = CAST(T_KEYWORDS AS CHAR(20 BYTE))))
--                    OR( 1 = 2 AND ( '' IS NULL OR  UPPER(EDU_PUPIL.FULLNAME) LIKE '%' || UPPER('') || '%'))
--                    OR( 1 = 3 AND ( '' IS NULL OR EDU_PUPIL.IDCARD = CAST('' AS CHAR(20 BYTE)))
--                  )

 ORDER BY
                schoolclassname,
                FIRSTNAME,
                LASTNAME,
                BIRTHDAY,
--                SCHOOLCLASSID,
--                CASE
--                   WHEN ORDERINDEX = 0 THEN 1000
--                   ELSE ORDERINDEX
--                END,
                NLSSORT(NLS_LOWER(FIRSTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                NLSSORT(NLS_LOWER(LASTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                BIRTHDAY;
       --)