
SELECT    DISTINCT
                  EDU_PUPIL.PUPILID,                
                  EDU_PUPIL.LASTNAME , 
                  EDU_PUPIL.FIRSTNAME,   
                  DECODE(EDU_PUPIL.GENDER, 0 , 'Nam', 'N?') GENDERNAME,   
                  PL_ETHNICITY.ETHNICITYNAME    ,           
                  TO_CHAR(EDU_PUPIL.BIRTHDAY, 'MM/DD/YYYY') BIRTHDAY,           
                  CASE
                    WHEN PLACEOFBIRTHCOUNTRYID = 250 THEN
                      PLACEOFBIRTHROVINCE.PROVINCENAME
                    ELSE
                      PLACEOFBIRTHCOUNTRY.COUNTRYNAME
                  END PLACEOFBIRTHFULL,
                  
                  NVL(EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME, EDU_PUPIL.DESCRIPTION) CURRENTSCHOOLCLASSNAME ,
                  LTRIM((NVL2( EDU_PUPIL.PERMANENTADDRESS,  EDU_PUPIL.PERMANENTADDRESS, '')
                  || NVL2(PERMANENTVILLAGEPUPIL.VILLAGENAME, ', ' || PERMANENTVILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(PERMANENTHAMLETPUPIL.HAMLETNAME, ', ' || PERMANENTHAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(PERMANENTWARDPUPIL.WARDNAME, ', ' || PERMANENTWARDPUPIL.WARDNAME, '')
                  || NVL2(PERMANENTDISTRICTPUPIL.DISTRICTNAME, ', ' || PERMANENTDISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PERMANENTPROVINCEPUPIL.PROVINCENAME, ', ' || PERMANENTPROVINCEPUPIL.PROVINCENAME, '')), ',')PERMANENTFULLADDRESS,
                  
                  LTRIM((NVL2(EDU_PUPIL.ADDRESS, EDU_PUPIL.ADDRESS, '')
                  || NVL2(VILLAGEPUPIL.VILLAGENAME, ', ' || VILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(HAMLETPUPIL.HAMLETNAME, ', ' || HAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(WARDPUPIL.WARDNAME, ', ' || WARDPUPIL.WARDNAME, '')
                  || NVL2(DISTRICTPUPIL.DISTRICTNAME, ', ' || DISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PROVINCEPUPIL.PROVINCENAME, ', ' || PROVINCEPUPIL.PROVINCENAME, '')), ',') FULLADDRESS,  
                  MD_FOREIGNLANGUAGECENTER.FOREIGNLANGUAGERCENTERNAME
                  ,NVL(EDU_SCHOOL.SCHOOLNAME, EDU_PUPIL.DESCRIPTION) CURRENTSCHOOLNAME     
                  ,SCHOOLDISTRICT.DISTRICTNAME
                  
        FROM      SAMS.EDU_PUPIL
        JOIN      
            (
              SELECT DISTINCT
                  PUPILID
                  ,SCHOOLID
--                  ,MOVETOSCHOOLID
--                  ,SCHOOLCLASSID
--              
                FROM sams.EDU_PUPIL_STUDYTIMELINE
                WHERE SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 21
                                AND SAMS.EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 2
                                AND EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
                                AND EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
                                AND EDU_PUPIL_STUDYTIMELINE.currentpupilstatusid = 1
                
             ) EDU_PUPIL_STUDYTIMELINE
  
   
          ON      EDU_PUPIL_STUDYTIMELINE.PUPILID =  EDU_PUPIL.PUPILID
          AND     edu_pupil_studytimeline.schoolid =   EDU_PUPIL.currentschoolid
        LEFT
        JOIN      SAMS.EDU_SCHOOL
          ON      EDU_SCHOOL.SCHOOLID = EDU_PUPIL_STUDYTIMELINE.SCHOOLID
         
        LEFT
        JOIN      SAMS.MD_DISTRICT SCHOOLDISTRICT
          ON      EDU_SCHOOL.DISTRICTID = SCHOOLDISTRICT.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD SCHOOLWARD
          ON      EDU_SCHOOL.WARDID = SCHOOLWARD.WARDID
        LEFT
        JOIN      SAMS.EDU_SCHOOLCLASS_NEW
                ON      EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID = EDU_PUPIL.currentschoolclassid
                AND     EDU_SCHOOLCLASS_NEW.ISACTIVE = 1 AND EDU_SCHOOLCLASS_NEW.ISDELETED = 0
                AND EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 21
                AND EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 2
        LEFT JOIN SAMS.EDU_SUBJECTSECTION
          ON    EDU_SUBJECTSECTION.SUBJECTSECTIONID = EDU_SCHOOLCLASS_NEW.SUBJECTSECTIONID
          AND   EDU_SUBJECTSECTION.ISDELETED = 0 AND EDU_SUBJECTSECTION.ISACTIVE = 1  
             
        
        LEFT
        JOIN      SAMS.EDU_CLASS
          ON      EDU_CLASS.CLASSID = EDU_SCHOOLCLASS_NEW.CLASSID
          AND     EDU_CLASS.ISACTIVE = 1 AND EDU_CLASS.ISDELETED = 0
        LEFT
        JOIN      SAMS.EDU_CLASS EDU_CLASS_PUPIL
          ON      EDU_CLASS_PUPIL.CLASSID = EDU_PUPIL.CURRENTCLASSID
        LEFT
        JOIN      SAMS.EDU_EDUCATIONLEVEL
          ON      EDU_CLASS.EDUCATIONLEVELID =EDU_EDUCATIONLEVEL.EDUCATIONLEVELID

        LEFT
        JOIN      SAMS.SYS_USER PUPILCREATEUSER
          ON      PUPILCREATEUSER.USERNAME = EDU_PUPIL.CREATEDUSER
        LEFT
        JOIN      SAMS.SYS_USER PUPILUPDATEDUSER
          ON      PUPILUPDATEDUSER.USERNAME = EDU_PUPIL.UPDATEDUSER
        LEFT
        JOIN      SAMS.SYS_USER PUPILDELETEDUSER
          ON      PUPILDELETEDUSER.USERNAME = EDU_PUPIL.DELETEDUSER
        LEFT
        JOIN      SAMS.MD_PROVINCE PERMANENTPROVINCEPUPIL
          ON      EDU_PUPIL.PERMANENTPROVINCEID = PERMANENTPROVINCEPUPIL.PROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT PERMANENTDISTRICTPUPIL
          ON      EDU_PUPIL.PERMANENTDISTRICTID = PERMANENTDISTRICTPUPIL.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD PERMANENTWARDPUPIL
          ON      EDU_PUPIL.PERMANENTWARDID = PERMANENTWARDPUPIL.WARDID
        LEFT
        JOIN      SAMS.MD_HAMLET PERMANENTHAMLETPUPIL
          ON      EDU_PUPIL.PERMANENTHAMLETID = PERMANENTHAMLETPUPIL.HAMLETID
        LEFT
        JOIN      SAMS.MD_VILLAGE PERMANENTVILLAGEPUPIL
          ON      EDU_PUPIL.PERMANENTVILLAGEID = PERMANENTVILLAGEPUPIL.VILLAGEID
        LEFT
        JOIN      SAMS.MD_PROVINCE PROVINCEPUPIL
          ON      EDU_PUPIL.PROVINCEID = PROVINCEPUPIL.PROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT DISTRICTPUPIL
          ON      EDU_PUPIL.DISTRICTID = DISTRICTPUPIL.DISTRICTID
        LEFT
        JOIN      SAMS.MD_WARD WARDPUPIL
          ON      EDU_PUPIL.WARDID = WARDPUPIL.WARDID
        LEFT
        JOIN      SAMS.MD_HAMLET HAMLETPUPIL
          ON      EDU_PUPIL.HAMLETID = HAMLETPUPIL.HAMLETID
        LEFT
        JOIN      SAMS.MD_VILLAGE VILLAGEPUPIL
          ON      EDU_PUPIL.VILLAGEID = VILLAGEPUPIL.VILLAGEID
        LEFT
        JOIN      SAMS.MD_JOB MJF
          ON      MJF.JOBID = EDU_PUPIL.FATHERJOBID
        LEFT
        JOIN      SAMS.MD_JOB MJM
          ON      MJM.JOBID = EDU_PUPIL.MOTHERJOBID
        LEFT
        JOIN      SAMS.PL_ETHNICITY
          ON      EDU_PUPIL.ETHNICITYID = PL_ETHNICITY.ETHNICITYID
        LEFT
        JOIN      SAMS.MD_COUNTRY BIRTHCOUNTRY
          ON      BIRTHCOUNTRY.COUNTRYID = EDU_PUPIL.BIRTHCOUNTRYID
        LEFT
        JOIN      SAMS.MD_PROVINCE BIRTHPROVINCE
          ON      BIRTHPROVINCE.PROVINCEID = EDU_PUPIL.BIRTHPROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT BIRTHDISTRICT
          ON      BIRTHDISTRICT.DISTRICTID = EDU_PUPIL.BIRTHDISTRICTID
        LEFT
        JOIN      SAMS.MD_COUNTRY PLACEOFBIRTHCOUNTRY
          ON      PLACEOFBIRTHCOUNTRY.COUNTRYID = EDU_PUPIL.PLACEOFBIRTHCOUNTRYID
        LEFT
        JOIN      SAMS.MD_PROVINCE PLACEOFBIRTHROVINCE
          ON      PLACEOFBIRTHROVINCE.PROVINCEID = EDU_PUPIL.PLACEOFBIRTHPROVINCEID
        LEFT
        JOIN      SAMS.MD_DISTRICT PLACEOFBIRTHDISTRICT
          ON      PLACEOFBIRTHDISTRICT.DISTRICTID = EDU_PUPIL.PLACEOFBIRTHDISTRICTID
        LEFT
        JOIN      SAMS.MD_FOREIGNLANGUAGECENTER
          ON      MD_FOREIGNLANGUAGECENTER.FOREIGNLANGUAGERCENTERID = EDU_PUPIL.FOREIGNLANGUAGERCENTERID
          AND     MD_FOREIGNLANGUAGECENTER.ISACTIVE = 1 AND MD_FOREIGNLANGUAGECENTER.ISDELETED = 0
      

        WHERE     EDU_PUPIL.ISDELETED = 0
        AND EDU_PUPIL.isactive = 1 
        AND EDU_PUPIL.ISDISABILITYPUPIL =0
        AND EDU_PUPIL.FOREIGNLANGUAGERCENTERID >0
        AND EDU_PUPIL.FOREIGNLANGUAGERCENTERID IS NOT NULL
        AND edu_pupil.currentclassid IN (8)
        AND edu_pupil.currentpupilstatusid = 1
        AND edu_pupil.currentschoolid NOT IN (1592,1593,1594,1595,1596,1597,1598,1599,1600,1605,1607,1610,1618,1613,1614,1616,1608,1611,1615,1602,1603,1604,1609,1617,1601,1606,1612,1524,1530,10112318,1525,1515,1470,1528,1469) 
 
 ORDER BY
                SCHOOLDISTRICT.DISTRICTNAME,
                CURRENTSCHOOLNAME,
                FIRSTNAME,
                LASTNAME,
                BIRTHDAY,
                NLSSORT(NLS_LOWER(FIRSTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                NLSSORT(NLS_LOWER(LASTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                BIRTHDAY;