 SELECT DISTINCT 
        '' STT,
        DISTRICT_SCHOOLNAME,
        schoolname,
        schoolclassname,
        pupilid
        ,fullname
        ,gender
        ,ngay_sinh
        ,placeofbirthprovincename
        ,birthplace
        ,contactphone
        ,provincename
        ,districtname
        ,wardname
        ,hamletname,
        fulladdress
        ,ethnicityname
        ,fatherfullname,fatherjobname,namsinh_cha
        ,motherfullname,motherjobname,namsinh_me,
        guardianfullname,guardianjobname,namsinh_ngh
        ,KHUYET_TAT,tbbb,lietsy,ah
        ,PERMANENTPROVINCE_PUPIL
        ,CASE WHEN ismemberofyouthunion = 1  THEN 'X' ELSE ' ' END DOAN_VIEN,
        '' CHUYENDEN,'' NGAYCHUYENDEN,'' CHUYEN_DI,'' ESCHOOL,idcard
      FROM(

        SELECT 
            DISTRICTSCHOOLNAME.districtname DISTRICT_SCHOOLNAME,
            es.schoolname,

            EDU_PUPIL.PUPILID,
            EDU_PUPIL.FULLNAME,
            EDU_PUPIL.FIRSTNAME,
            EDU_PUPIL.LASTNAME,
            DECODE(EDU_PUPIL.GENDER,0, 'Nam', 1, 'Nữ') GENDER,
            TO_CHAR(EDU_PUPIL.fatherbirthday,'YYYY') NAMSINH_CHA,
            TO_CHAR(EDU_PUPIL.motherbirthday,'YYYY') NAMSINH_ME,
            TO_CHAR(EDU_PUPIL.guardianbirthday,'DD/MM/YYYY') NAMSINH_NGH,
            TO_CHAR(EDU_PUPIL.BIRTHDAY,'DD/MM/YYYY') NGAY_SINH,
            EDU_PUPIL.PLACEOFBIRTHFULL,
            EDU_PUPIL.CURRENTSCHOOLID,
            EDU_PUPIL.CURRENTSCHOOLCLASSID,
            EDU_SCHOOLCLASS_NEW.SCHOOLCLASSNAME,
            EDU_PUPIL.CREATEDUSER,
            EDU_PUPIL.CREATEDDATE,
            '' CREATEDUSERFULLNAME,
            EDU_PUPIL.IDCARD,
            EDU_PUPIL.ETHNICITYID,
            PL_ETHNICITY.ETHNICITYNAME,
            EDU_PUPIL.NATIONLATYID,
            EDU_PUPIL.PLACEOFBIRTHCOUNTRYID,
            --N?U KH�NG PH?I QU?C GIA VN THI L?Y NOI SINH L� QU?C GIA NGU?C L?I L?Y T?NH TH�NH L�M NOI SINH
            DECODE(EDU_PUPIL.PLACEOFBIRTHCOUNTRYID, 250, PROVINCEPB.PROVINCENAME, MD_COUNTRY.COUNTRYNAME) AS PLACEOFBIRTHPROVINCENAME,
            EDU_PUPIL.PLACEOFBIRTHPROVINCEID,
            EDU_PUPIL.PLACEOFBIRTHDISTRICTID,
            EDU_PUPIL.PLACEOFBIRTHWARDID,
            EDU_PUPIL.PLACEOFBIRTH,
            EDU_PUPIL.BIRTHCOUNTRYID,
            EDU_PUPIL.BIRTHPROVINCEID,
            EDU_PUPIL.BIRTHDISTRICTID,
            EDU_PUPIL.BIRTHWARDID,
            --�i�`u chi?nh cho gi��ng app
            DECODE(EDU_PUPIL.PLACEOFBIRTHCOUNTRYID, 250, BIRTHPROVINCE.PROVINCENAME, MD_COUNTRY.COUNTRYNAME) AS BIRTHPLACE,
            --EDU_PUPIL.BIRTHPLACE,
            EDU_PUPIL.CURRENTPUPILSTATUSID,
            EDU_PUPIL.ADMISSIONSELECTEDTYPEID,
            EDU_PUPIL.PUPILRESIDENTTYPEID,
            EDU_PUPIL.CONTACTPROVINCEID,
            EDU_PUPIL.CONTACTDISTRICTID,
            EDU_PUPIL.CONTACTWARDID,
            EDU_PUPIL.CONTACTPHONE,
            EDU_PUPIL.PERMANENTPROVINCEID,
            EDU_PUPIL.PERMANENTDISTRICTID,
            EDU_PUPIL.PERMANENTWARDID,
            EDU_PUPIL.PERMANENTHAMLETID,
            PERMANENTPROVINCEPUPIL.provincename PERMANENTPROVINCE_PUPIL,
            LTRIM((NVL2(PERMANENTADDRESS, PERMANENTADDRESS, '')
                  || NVL2(PERMANENTVILLAGEPUPIL.VILLAGENAME, ', ' || PERMANENTVILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(PERMANENTHAMLETPUPIL.HAMLETNAME, ', ' || PERMANENTHAMLETPUPIL.HAMLETNAME, '')
                  || NVL2(PERMANENTWARDPUPIL.WARDNAME, ', ' || PERMANENTWARDPUPIL.WARDNAME, '')
                  || NVL2(PERMANENTDISTRICTPUPIL.DISTRICTNAME, ', ' || PERMANENTDISTRICTPUPIL.DISTRICTNAME, '')
                  || NVL2(PERMANENTPROVINCEPUPIL.PROVINCENAME, ', ' || PERMANENTPROVINCEPUPIL.PROVINCENAME, '')), ',')PERMANENTFULLADDRESS,
--            EDU_PUPIL.PERMANENTFULLADDRESS,
            EDU_PUPIL.PROVINCEID,
            PROVINCE.PROVINCENAME,
            EDU_PUPIL.DISTRICTID,
            DISTRICT.DISTRICTNAME,
            EDU_PUPIL.WARDID,
            WARD.WARDNAME,
            EDU_PUPIL.HAMLETID,
            HAMLET.HAMLETNAME,

             LTRIM((NVL2(EDU_PUPIL.ADDRESS, EDU_PUPIL.ADDRESS, '')
                  || NVL2(VILLAGEPUPIL.VILLAGENAME, ', ' || VILLAGEPUPIL.VILLAGENAME, '')
                  || NVL2(HAMLET.HAMLETNAME, ', ' || HAMLET.HAMLETNAME, '')
                  || NVL2(WARD.WARDNAME, ', ' || WARD.WARDNAME, '')
                  || NVL2(DISTRICT.DISTRICTNAME, ', ' || DISTRICT.DISTRICTNAME, '')
                  || NVL2(PROVINCE.PROVINCENAME, ', ' || PROVINCE.PROVINCENAME, '')), ',') FULLADDRESS,

--            EDU_PUPIL.FULLADDRESS,
            EDU_PUPIL.ISDELETED,
            EDU_PUPIL.ORDERINDEX,
            EDU_PUPIL.CURRENTCLASSID,
            EDU_PUPIL.FATHERFULLNAME,
            EDU_PUPIL.FATHERBIRTHDAY,
            EDU_PUPIL.FATHERJOBID,
            NVL(MJFATHER.JOBNAME,EDU_PUPIL.FATHERJOBTITLE) AS FATHERJOBNAME,
            EDU_PUPIL.MOTHERFULLNAME,
            EDU_PUPIL.MOTHERBIRTHDAY,
            EDU_PUPIL.MOTHERJOBID,
            NVL(MJMOTHER.JOBNAME,EDU_PUPIL.MOTHERJOBTITLE) AS MOTHERJOBNAME,
            EDU_PUPIL.GUARDIANFULLNAME,
            EDU_PUPIL.GUARDIANBIRTHDAY,
            EDU_PUPIL.GUARDIANJOBID,
            NVL(MJGUARDIAN.JOBNAME,EDU_PUPIL.GUARDIANJOBTITLE) AS GUARDIANJOBNAME,
            MD_DISABILITYTYPE.DISABILITYTYPEID,
            MD_DISABILITYTYPE.DISABILITYTYPENAME,
            NVL(STATUSTIMELINE.BOOKDISPLAYTYPE,NVL(STATUSPUPIL.BOOKDISPLAYTYPE,1)) BOOKDISPLAYTYPE,
            NVL(STATUSTIMELINE.REPORTDISPLAYTYPE,NVL(STATUSPUPIL.REPORTDISPLAYTYPE,1)) REPORTDISPLAYTYPE,
            EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID SCHOOLCLASSIDBYTERM,
            EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID TIMELINESTATUS,
            EDU_PUPIL.ECONTACTBOOKPHONENUMBER,
            nvl(EDU_PUPIL.ISMEMBEROFYOUTHUNION,0) ISMEMBEROFYOUTHUNION,

            CASE WHEN EXISTS (SELECT 1 FROM SAMS.EDU_PUPIL_POLICYOBJECT EPP
                                WHERE PUPILID = EDU_PUPIL.PUPILID
                                AND POLICYOBJECTTYPEID IN (3))
            THEN 'X'
            ELSE ''
            END AS LIETSY,
            CASE WHEN EXISTS (SELECT 1 FROM SAMS.EDU_PUPIL_POLICYOBJECT EPP
                                WHERE PUPILID = EDU_PUPIL.PUPILID
                                AND POLICYOBJECTTYPEID IN (5,7,8))
            THEN 'X'
            ELSE ''
            END AS TBBB,
            CASE WHEN EXISTS (SELECT 1 FROM SAMS.EDU_PUPIL_POLICYOBJECT EPP
                                WHERE PUPILID = EDU_PUPIL.PUPILID
                                AND POLICYOBJECTTYPEID =2)
            THEN 'X'
            ELSE ''
            END AS AH,
            CASE WHEN EDU_PUPIL.ISDISABILITYPUPIL = 1  THEN 'X' ELSE ' ' END KHUYET_TAT
           
          FROM      SAMS.EDU_PUPIL_STUDYTIMELINE
          JOIN      SAMS.EDU_PUPIL
            ON      EDU_PUPIL_STUDYTIMELINE.PUPILID = EDU_PUPIL.PUPILID
            AND     EDU_PUPIL_STUDYTIMELINE.schoolid =edu_pupil.currentschoolid 
           AND      EDU_PUPIL.ISACTIVE = 1
           AND      EDU_PUPIL.ISDELETED = 0
           JOIN SAMS.EDU_SCHOOL ES
                ON ES.SCHOOLID = EDU_PUPIL_STUDYTIMELINE.schoolid
                AND ES.ISACTIVE = 1 AND ES.ISDELETED = 0
          LEFT JOIN sams.md_district DISTRICTSCHOOLNAME
            ON DISTRICTSCHOOLNAME.districtid = es.districtid
            AND DISTRICTSCHOOLNAME.isactive = 1 AND DISTRICTSCHOOLNAME.isdeleted = 0
           JOIN SAMS.EDU_SCHOOL_EDUCATIONLEVEL ESE
            ON ESE.SCHOOLID = ES.SCHOOLID
     LEFT JOIN      SAMS.EDU_SCHOOLCLASS_NEW
            ON      EDU_PUPIL_STUDYTIMELINE.SCHOOLCLASSID = EDU_SCHOOLCLASS_NEW.SCHOOLCLASSID
           AND      EDU_SCHOOLCLASS_NEW.ISDELETED = 0
           AND      EDU_SCHOOLCLASS_NEW.SCHOOLYEARID = 21 -- param: năm học
           AND      EDU_SCHOOLCLASS_NEW.SCHOOLTERMID = 2
    LEFT JOIN       SAMS.MD_JOB MJFATHER
           ON       MJFATHER.JOBID = EDU_PUPIL.FATHERJOBID AND MJFATHER.ISACTIVE = 1 AND MJFATHER.ISDELETED = 0
    LEFT JOIN       SAMS.MD_JOB MJMOTHER
           ON       MJMOTHER.JOBID = EDU_PUPIL.MOTHERJOBID AND MJMOTHER.ISACTIVE = 1 AND MJMOTHER.ISDELETED = 0
    LEFT JOIN       SAMS.MD_JOB MJGUARDIAN
           ON       MJGUARDIAN.JOBID = EDU_PUPIL.GUARDIANJOBID AND MJGUARDIAN.ISACTIVE = 1 AND MJGUARDIAN.ISDELETED = 0
    LEFT JOIN       SAMS.PL_ETHNICITY
           ON       PL_ETHNICITY.ETHNICITYID = EDU_PUPIL.ETHNICITYID AND PL_ETHNICITY.ISACTIVE = 1 AND PL_ETHNICITY.ISDELETED = 0
    LEFT JOIN       SAMS.MD_COUNTRY
           ON       EDU_PUPIL.PLACEOFBIRTHCOUNTRYID = MD_COUNTRY.COUNTRYID AND MD_COUNTRY.ISACTIVE = 1 AND MD_COUNTRY.ISDELETED = 0

    LEFT JOIN       SAMS.MD_PROVINCE PROVINCEPB -- T?nh th�nh noi sinh
           ON       PROVINCEPB.PROVINCEID = EDU_PUPIL.PLACEOFBIRTHPROVINCEID AND PROVINCEPB.ISACTIVE = 1 AND PROVINCEPB.ISDELETED = 0
    LEFT JOIN       SAMS.MD_PROVINCE PROVINCE
           ON       PROVINCE.PROVINCEID = EDU_PUPIL.PROVINCEID AND PROVINCE.ISACTIVE = 1 AND PROVINCE.ISDELETED = 0
    LEFT JOIN       SAMS.MD_PROVINCE BIRTHPROVINCE
           ON       BIRTHPROVINCE.PROVINCEID = EDU_PUPIL.BIRTHPROVINCEID
    LEFT JOIN       SAMS.MD_DISTRICT DISTRICT
           ON       DISTRICT.DISTRICTID = EDU_PUPIL.DISTRICTID AND DISTRICT.ISACTIVE = 1 AND DISTRICT.ISDELETED = 0
    LEFT JOIN       SAMS.MD_WARD WARD
           ON       WARD.WARDID = EDU_PUPIL.WARDID AND WARD.ISACTIVE = 1 AND WARD.ISDELETED = 0
    LEFT JOIN       SAMS.MD_HAMLET HAMLET
           ON       HAMLET.HAMLETID = EDU_PUPIL.HAMLETID AND HAMLET.ISDELETED = 0 AND HAMLET.ISACTIVE = 1
    LEFT
         JOIN      SAMS.MD_VILLAGE VILLAGEPUPIL
           ON      VILLAGEPUPIL.VILLAGEID = EDU_PUPIL.VILLAGEID
          -- BO SUNG HO KHAU THUONG TRU
    LEFT
         JOIN      SAMS.MD_PROVINCE PERMANENTPROVINCEPUPIL
           ON      EDU_PUPIL.PERMANENTPROVINCEID = PERMANENTPROVINCEPUPIL.PROVINCEID
    LEFT
         JOIN      SAMS.MD_DISTRICT PERMANENTDISTRICTPUPIL
           ON      EDU_PUPIL.PERMANENTDISTRICTID = PERMANENTDISTRICTPUPIL.DISTRICTID
          AND     PERMANENTDISTRICTPUPIL.isactive =  1 AND PERMANENTDISTRICTPUPIL.isdeleted = 0
         LEFT
         JOIN      SAMS.MD_WARD PERMANENTWARDPUPIL
           ON      EDU_PUPIL.PERMANENTWARDID = PERMANENTWARDPUPIL.WARDID
           AND     PERMANENTWARDPUPIL.isactive =  1 AND PERMANENTWARDPUPIL.isdeleted = 0
          LEFT
          JOIN      SAMS.MD_HAMLET PERMANENTHAMLETPUPIL
            ON      EDU_PUPIL.PERMANENTHAMLETID = PERMANENTHAMLETPUPIL.HAMLETID
          LEFT
          JOIN      SAMS.MD_VILLAGE PERMANENTVILLAGEPUPIL
            ON      EDU_PUPIL.PERMANENTVILLAGEID = PERMANENTVILLAGEPUPIL.VILLAGEID

    LEFT JOIN       SAMS.MD_DISABILITYTYPE
           ON       EDU_PUPIL.DISABILITYTYPEID = MD_DISABILITYTYPE.DISABILITYTYPEID
    LEFT JOIN       SAMS.EDU_PUPILSTATUS STATUSTIMELINE
           ON       EDU_PUPIL_STUDYTIMELINE.CURRENTPUPILSTATUSID = STATUSTIMELINE.PUPILSTATUSID
          AND       STATUSTIMELINE.ISDELETED = 0
          AND       STATUSTIMELINE.ISACTIVE = 1
    LEFT JOIN       SAMS.EDU_PUPILSTATUS STATUSPUPIL
           ON       EDU_PUPIL.CURRENTPUPILSTATUSID = STATUSPUPIL.PUPILSTATUSID
          AND       STATUSPUPIL.ISDELETED = 0
          AND       STATUSPUPIL.ISACTIVE = 1
    LEFT JOIN       SAMS.EDU_CLASS
           ON       EDU_CLASS.CLASSID = EDU_SCHOOLCLASS_NEW.CLASSID
          AND       EDU_CLASS.ISACTIVE = 1 AND EDU_CLASS.ISDELETED = 0
--
        WHERE       EDU_PUPIL.ISDELETED = 0
          AND       (STATUSTIMELINE.BOOKDISPLAYTYPE IS NULL OR STATUSTIMELINE.BOOKDISPLAYTYPE <> 3)
          AND       EDU_PUPIL.ISACTIVE = 1


         --CODE M?I L?Y DANH S�CH HS C? L?P -1  V� L?P �� CH?N

         
          AND EDU_PUPIL_STUDYTIMELINE.SCHOOLYEARID = 21 -- param: năm học
          AND EDU_PUPIL_STUDYTIMELINE.SCHOOLTERMID = 2
          AND EDU_PUPIL_STUDYTIMELINE.ISACTIVE = 1
          AND EDU_PUPIL_STUDYTIMELINE.ISDELETED = 0
          AND ES.schoolid NOT IN (1592,1593,1594,1595,1596,1597,1598,1599,1600,1605,1607,1610,1618,1613,1614,1616,1608,1611,1615,1602,1603,1604,1609,1617,1601,1606,1612,1524,1530,10112318,1525,1515,1470,1528,1469)
         -- Bo sung lay them trang thai hoc sinh
          AND ESE.EDUCATIONLEVELID IN(4,7)
          AND edu_pupil.CURRENTCLASSID IN (15,18)
          AND edu_pupil.currentpupilstatusid = 1
          AND EDU_PUPIL_STUDYTIMELINE.currentpupilstatusid = 1
 ORDER BY
                DISTRICTSCHOOLNAME.districtname,
                ES.schoolname,               
                FIRSTNAME,
                LASTNAME,
                NLSSORT(NLS_LOWER(FIRSTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                NLSSORT(NLS_LOWER(LASTNAME, 'NLS_SORT=vietnamese'), 'NLS_SORT=vietnamese'),
                edu_pupil.birthday
                
      )
   