SELECT 
  
  SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID MA_KY,
  SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMNAME TEN_KY,
  COUNT(ADMISSIONREGISTERID) SL,
  CASE WHEN EGOVCHANELID = 1 THEN 'TRUC_TIEP' ELSE 'TRUC_TUYEN' END KENH_DANG_KY


  FROM SAMS.EDU_ADMISSIONREGISTER
JOIN SAMS.EDU_ADMISSIONTERM
  ON SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID = SAMS.EDU_ADMISSIONREGISTER.ADMISSIONTERMID
  WHERE SAMS.EDU_ADMISSIONREGISTER.ISACTIVE = 1
  AND SAMS.EDU_ADMISSIONREGISTER.ISDELETED =0 
--  AND TO_CHAR(EDU_ADMISSIONREGISTER.registerdate, 'YYYYMMDD') >= '20180101'
  GROUP BY  SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID,SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMNAME,EGOVCHANELID

ORDER BY EDU_ADMISSIONTERM.ADMISSIONTERMID;

SELECT 
  
  SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID MA_KY,
  SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMNAME TEN_KY,
  COUNT(ADMISSIONREGISTERID) SL,
  CASE WHEN EGOVCHANELID = 1 THEN 'TRUC_TIEP' ELSE 'TRUC_TUYEN' END KENH_DANG_KY


  FROM SAMS.EDU_ADMISSIONREGISTER
JOIN SAMS.EDU_ADMISSIONTERM
  ON SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID = SAMS.EDU_ADMISSIONREGISTER.ADMISSIONTERMID
  WHERE SAMS.EDU_ADMISSIONREGISTER.ISACTIVE = 1
  AND SAMS.EDU_ADMISSIONREGISTER.ISDELETED =0 
--AND TO_CHAR(EDU_ADMISSIONREGISTER.registerdate, 'YYYYMMDD') >= '20180101'
  GROUP BY  SAMS.EDU_ADMISSIONTERM.SCHOOLYEARID,SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMNAME,EGOVCHANELID, SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID

ORDER BY EDU_ADMISSIONTERM.ADMISSIONTERMID;


SELECT  
  SAMS.EDU_ADMISSIONTERM.SCHOOLYEARID,
  COUNT(ADMISSIONREGISTERID) SL,
  CASE WHEN EGOVCHANELID = 1 THEN 'TRUC_TIEP' ELSE 'TRUC_TUYEN' END KENH_DANG_KY


  FROM SAMS.EDU_ADMISSIONREGISTER
JOIN SAMS.EDU_ADMISSIONTERM
  ON SAMS.EDU_ADMISSIONTERM.ADMISSIONTERMID = SAMS.EDU_ADMISSIONREGISTER.ADMISSIONTERMID
JOIN SAMS.EDU_SCHOOLYEAR
  ON SAMS.EDU_SCHOOLYEAR.SCHOOLYEARID = SAMS.EDU_ADMISSIONTERM.SCHOOLYEARID
  WHERE SAMS.EDU_ADMISSIONREGISTER.ISACTIVE = 1
  AND SAMS.EDU_ADMISSIONREGISTER.ISDELETED =0 

  GROUP BY  SAMS.EDU_ADMISSIONTERM.SCHOOLYEARID,EGOVCHANELID

;