 SELECT DISTINCT
    TEMP.PUPILID
    ,FULLNAME
    ,GENDER
    ,BIRTHDAY
    ,PLACEOFBIRTHFULL
    ,ETHNICITYNAME
    ,FULLADDRESS
    ,FATHERFULLNAME
    ,FATHERJOBNAME
    ,MOTHERFULLNAME
    ,MOTHERJOBNAME
    ,GUARDIANFULLNAME
    ,GUARDIANJOBNAME
    ,SCHOOLNAME
    ,TITLESCHOOLNAME
    ,WARDNAME
    ,NVL(DISTRICTNAME,'...................................')DISTRICTNAME
    ,NVL(TRIM(TITLEDISTRICTNAME),'....................')TITLEDISTRICTNAME
    ,NVL(PROVINCENAME,'...................................')PROVINCENAME
    ,SCHOOLHISTORYNAME
    ,UPPER(FIRSTTERMSTUDYRANK) FIRSTTERMSTUDYRANK
    ,UPPER(SECONDTERMSTUDYRANK)SECONDTERMSTUDYRANK
    ,UPPER(WHOLEYEARSTUDYRANK) WHOLEYEARSTUDYRANK
    ,UPPER(FIRSTTERMCONDUCTRANK) FIRSTTERMCONDUCTRANK
    ,UPPER(SECONDTERMCONDUCTRANK) SECONDTERMCONDUCTRANK
    ,UPPER(WHOLEYEARCONDUCTRANK) WHOLEYEARCONDUCTRANK
    ,TOTALSCHOOLABSENTDAYS
    ,RECHECKSTUDYRANK
    ,RETRAINCONDUCTRANK
    ,HEADTEACHERREMARKCONTENT
    ,HEADTEACHERNAME
    ,HEADTEACHERNAMEORI
    ,SUPRINCIPALFULLNAME
    ,NVL(EDUCATIONLEVELID,4) EDUCATIONLEVELID
    ,EDUCATIONLEVEL
    ,SHORTEDUCATIONLEVEL
    ,TITLEBONUS
    ,TEMP.SCHOOLCLASSID
    ,TRIM(SCHOOLCLASSNAME) SCHOOLCLASSNAME
    ,FIRSTTERMMARK
    ,SECONDTERMMARK
    ,WHOLEYEARMARK
    ,FIRSTTERMAVERAGEMARK
    ,SECONDTERMAVERAGEMARK
    ,WHOLEYEARAVERAGEMARK
    ,POLICYOBJECTLIST
    ,SUBJECTSECTIONNAME
    ,COUNTATT_PER
    ,COUNTATT_NOPER
    ,ABSENTCOUNT
    ,TEMP.SUBJECTID
    ,TEACHERFULLNAME
    ,PRIZECONTENT
    ,OTHERREWARD
    ,PRINCIPALAPPROVECONTENT
    ,PRINCIPALAPPROVEDATE
    ,
        CASE WHEN ISRECHECK = 0 AND ISRETRAIN = 0 THEN PASSCLASSCOMMENT
        ELSE '....................................' END
        PASSCLASSCOMMENT

    ,CASE WHEN ISRECHECK = 0 THEN NOPASSCLASSCOMMENT
      WHEN ISRECHECK = 1 AND EDU_PASSCLASSTYPEISPASSCLASS = 0 AND PASSCLASSPUPILISPASSCLASS =1
          THEN 'Không du?c lên l?p '|| TO_NUMBER(trim(regexp_replace(CLASSNAME, '[[:alpha:]]|_') + 1))
        ELSE '....................................' END NOPASSCLASSCOMMENT
    --,'' NOPASSCLASSCOMMENT
    ,OCCUPATIONSUBJECTNAME
    ,OCCUPATIONRESULTNAME
    ,UPPER(RECHECKCONDUCTRANKNAME) RECHECKCONDUCTRANKNAME
    ,UPPER(RECHECKSTUDYRANKNAME) RECHECKSTUDYRANKNAME
    ,(CASE WHEN SUBJECTASSESSTYPEID = 1 THEN
              REPLACE(rtrim(to_char(RECHECKMARK, 'FM90.099'),',' ),'.',',')
              ELSE DECODE(RECHECKMARK,0 ,'CÐ',1,'Ð',2,'M','' ) END )RECHECKMARK
    ,REPLACE(rtrim(to_char(RECHECKAVERAGEMARK, 'FM90.099'),',' ),'.',',') RECHECKAVERAGEMARK
    ,EDU_PASSCLASSTYPEISPASSCLASS
    ,PASSCLASSPUPILISPASSCLASS
    ,EDU_PUPIL_RECHECKSUBJECT.PUPILID
    ,SUBJECTNAME
    ,SUBJECTINDEX
    ,ISRECHECK
    ,CASE WHEN (ISRECHECK = 1 OR ISRETRAIN = 1) AND EDU_PASSCLASSTYPEISPASSCLASS = 1 AND PASSCLASSPUPILISPASSCLASS =1
          THEN (
            CASE
              WHEN TO_NUMBER(trim(regexp_replace(CLASSNAME, '[[:alpha:]]|_'))) = 12 THEN 'Ð? di?u ki?n d? thi THPT Qu?c Gia'
              WHEN TO_NUMBER(trim(regexp_replace(CLASSNAME, '[[:alpha:]]|_'))) = 9 THEN 'Ð? di?u ki?n xét TN'
              ELSE 'Ðu?c lên l?p '|| TO_NUMBER(trim(regexp_replace(CLASSNAME, '[[:alpha:]]|_')) + 1) END
          )
          ELSE '....................................'
          END RECHECKRESULT
    --,'' RECHECKRESULT
    ,SCHOOLYEAR_ID SCHOOLYEARID
    ,SCHOOLYEARNAME
    ,PRINCIPALSIGNDATE
    /*Ðiê`u chi?nh lâ´y uu tiên tu` ba?ng studybookinfo*/
-- ,NVL(T_PRINCIPALUSERNAME, PRINCIPALFULLNAME)PRINCIPALFULLNAME
--   ,NVL(PRINCIPALFULLNAME, T_PRINCIPALUSERNAME)PRINCIPALFULLNAME
    ,HEADTEACHERFULLNAME
    ,REGISTERBOOKNUMBER
    ,NVL(TO_CHAR(CLASSID),'0') CLASSID
    ,CLASSINDEX
    ,SCHOOLCLASSINDEX
    ,SCHOOLYEARINDEX
    ,CURRENTPUPILSTATUSID
    ,CLASSNAME
    ,SCHOOLCLASSNAMEFULL
    ,SIGNIFICATION
    ,WHOLEYEARSTUDYRANKID
    ,WHOLEYEARCONDUCTRANKID
    ,TO_CHAR(BEGINTERMDATE, 'dd/MM/YYYY') BEGINTERMDATE,
     TO_CHAR(ENDTERMDATE, 'dd/MM/YYYY') ENDTERMDATE
    ,NVL(TO_CHAR(BEGINTERMDATE, 'dd/MM/YYYY'),'..../..../.....') BEGINTERMDATE_1
        ,NVL(TO_CHAR(ENDTERMDATE, 'dd/MM/YYYY'),'..../..../.....') ENDTERMDATE_1
    FROM
    (
     SELECT
      DISTINCT
        EP.PUPILID,
        EP.FULLNAME,
        DECODE(EP.GENDER,0 ,'Nam',1,'N?') GENDER,
        --EP.BIRTHDAY,
        to_char( TO_timestamp(EP.BIRTHDAY),'dd') || ' tháng ' || to_char( TO_timestamp(EP.BIRTHDAY),'MM') || ' nam ' || to_char( TO_timestamp(EP.BIRTHDAY),'yyyy') BIRTHDAY,
        CASE WHEN PLACEOFBIRTHCOUNTRYID = 250
                       THEN   PLACEOFBIRTHROVINCE.PROVINCENAME
                       ELSE   PLACEOFBIRTHCOUNTRY.COUNTRYNAME
                       END PLACEOFBIRTHFULL
        --EP.PLACEOFBIRTHFULL,
        ,PL_ETHNICITY.ETHNICITYNAME,
        EP.FULLADDRESS,
        FATHERFULLNAME,

        DECODE(MJF.ISOTHER,1,EP.FATHERJOBTITLE,NVL2(MJF.JOBNAME,MJF.JOBNAME,EP.FATHERJOBTITLE)) FATHERJOBNAME,
        MOTHERFULLNAME,
        DECODE(MJM.ISOTHER,1,EP.MOTHERJOBTITLE,NVL2(MJM.JOBNAME,MJM.JOBNAME,EP.MOTHERJOBTITLE)) MOTHERJOBNAME,
        GUARDIANFULLNAME,
        DECODE(MJW.ISOTHER,1,EP.GUARDIANJOBTITLE,NVL2(MJW.JOBNAME,MJW.JOBNAME,EP.GUARDIANJOBTITLE)) GUARDIANJOBNAME,

      NVL(ES.SCHOOLNAME,EPS.SCHOOLNAME) SCHOOLNAME
      ,DECODE( INSTR(UPPER(ES.SCHOOLNAME), 'TRU?NG'),1,SUBSTR(ES.SCHOOLNAME,7),ES.SCHOOLNAME) TITLESCHOOLNAME
--      ,SCHOOLORGANWARD.WARDNAME WARDNAME
      --,REPLACE((replace(UPPER(replace(UPPER(SCHOOLORGANWARD.WARDNAME),'XÃ ','')),'PHU?NG ','')),'TH? TR?N ','') WARDNAME
      ,CASE
      WHEN INSTR(UPPER(SCHOOLORGANWARD.WARDNAME), 'PHU?NG') = 1 THEN SUBSTR(SCHOOLORGANWARD.WARDNAME,7)
      WHEN INSTR(UPPER(SCHOOLORGANWARD.WARDNAME), 'XÃ') = 1 THEN SUBSTR(SCHOOLORGANWARD.WARDNAME,3)
      WHEN INSTR(UPPER(SCHOOLORGANWARD.WARDNAME), 'TH? TR?N') = 1 THEN SUBSTR(SCHOOLORGANWARD.WARDNAME,9)
      ELSE SCHOOLORGANWARD.WARDNAME END WARDNAME
      ,SCHOOLORGANDISTRICT.DISTRICTNAME
      ,CASE
      WHEN INSTR(UPPER(SCHOOLORGANDISTRICT.DISTRICTNAME), 'QU?N') = 1 THEN SUBSTR(SCHOOLORGANDISTRICT.DISTRICTNAME,5)
      WHEN INSTR(UPPER(SCHOOLORGANDISTRICT.DISTRICTNAME), 'HUY?N') = 1 THEN SUBSTR(SCHOOLORGANDISTRICT.DISTRICTNAME,6)
      WHEN INSTR(UPPER(SCHOOLORGANDISTRICT.DISTRICTNAME), 'TH? XÃ') = 1 THEN SUBSTR(SCHOOLORGANDISTRICT.DISTRICTNAME,7)
      ELSE SCHOOLORGANDISTRICT.DISTRICTNAME END TITLEDISTRICTNAME
      --,replace(UPPER(replace(UPPER(MD.DISTRICTNAME),'HUY?N','')),'QU?N','') TITLEDISTRICTNAME
      ,MP.PROVINCENAME
      ,NVL2(EPS.SCHOOLNAME,EPS.SCHOOLNAME,ES.SCHOOLNAME ||  NVL2(SCHOOLORGANDISTRICT.DISTRICTNAME,', ' || SCHOOLORGANDISTRICT.DISTRICTNAME,'') || NVL2(SCHOOLORGANPROVINCE.PROVINCENAME,', ' || SCHOOLORGANPROVINCE.PROVINCENAME,''))  SCHOOLHISTORYNAME
      ,DECODE(EPS.FIRSTTERMSTUDYRANKID,1,'GI?I',2,'KHÁ',3,'TRUNG BÌNH',4 , 'Y?U',5,'KÉM','') FIRSTTERMSTUDYRANK
      ,DECODE(EPS.SECONDTERMSTUDYRANKID,1,'GI?I',2,'KHÁ',3,'TRUNG BÌNH',4 , 'Y?U',5,'KÉM','') SECONDTERMSTUDYRANK
      ,DECODE(EPS.WHOLEYEARSTUDYRANKID,1,'GI?I',2,'KHÁ',3,'TRUNG BÌNH',4 , 'Y?U',5,'KÉM','') WHOLEYEARSTUDYRANK
      ,UPPER(EC1.CONDUCTRANKNAME) FIRSTTERMCONDUCTRANK
      ,UPPER(EC2.CONDUCTRANKNAME )SECONDTERMCONDUCTRANK
      ,UPPER(EC3.CONDUCTRANKNAME) WHOLEYEARCONDUCTRANK
      ,TOTALSCHOOLABSENTDAYS
      ,DECODE(EPS.RECHECKSTUDYRANKID,1,'GI?I',2,'KHÁ',3,'TRUNG BÌNH',4 , 'Y?U',5,'KÉM','') RECHECKSTUDYRANK
      ,UPPER(EC4.CONDUCTRANKNAME) RETRAINCONDUCTRANK
      ,EDU_STUDYBOOKINFO.HEADTEACHERCOMMENT HEADTEACHERREMARKCONTENT
      ,'               ' || HEADTEACHERUSER.FULLNAME  HEADTEACHERNAME
      ,HEADTEACHERUSER.FULLNAME  HEADTEACHERNAMEORI
      ,SUPRINCIPAL.FULLNAME SUPRINCIPALFULLNAME  --HI?U TRU?NG
      ,ep.SUBJECTNAME
        ,ep.subjectassesstypeid
        ,ec.educationlevelid
        ,UPPER(DECODE(NVL(ec.educationlevelid,4),3,'TRUNG H?C CO S?',4,'TRUNG H?C PH? THÔNG',7,DECODE(-1,-2,'GDTX C?P TRUNG H?C CO S?',-3, 'GDTX C?P TRUNG H?C PH? THÔNG'))) EDUCATIONLEVEL
        ,NVL2(EDU_STUDYBOOKINFO.REGISTERBOOKNUMBER,(DECODE(NVL(ec.educationlevelid,4),3,'S?: ' || TRIM(EDU_STUDYBOOKINFO.REGISTERBOOKNUMBER) || '/THCS',4,'S?: ' || TRIM(EDU_STUDYBOOKINFO.REGISTERBOOKNUMBER) || '/THPT',7,DECODE(-1,-2,'S?: ' || TRIM(EDU_STUDYBOOKINFO.REGISTERBOOKNUMBER) || '/GDTX c?p THCS',-3,'S?: ' || TRIM(EDU_STUDYBOOKINFO.REGISTERBOOKNUMBER) || '/GDTX c?p THPT'))), (DECODE(NVL(ec.educationlevelid,4),3,'S?: ............/THCS',4,'S?: ............/THPT',7,DECODE(-1,-2,'S?: ............/GDTX c?p THCS',-3, 'S?: ............/GDTX c?p THPT')))) SHORTEDUCATIONLEVEL
        ,(DECODE(NVL(ec.educationlevelid,4),3,'Ðu?c gi?i thu?ng trong các k? thi t? c?p huy?n (qu?n, th? xã) tr? lên:',4,'Ðu?c gi?i thu?ng trong các k? thi t? c?p huy?n tr? lên:','')) TITLEBONUS
        ,NVL2(ES1.SCHOOLCLASSNAME,DECODE( INSTR(UPPER(ES1.SCHOOLCLASSNAME), 'L?P '),1,SUBSTR(ES1.SCHOOLCLASSNAME,4),ES1.SCHOOLCLASSNAME),DECODE( INSTR(UPPER(EPS.SCHOOLCLASSNAME), 'L?P '),1,SUBSTR(EPS.SCHOOLCLASSNAME,4),EPS.SCHOOLCLASSNAME)) SCHOOLCLASSNAME
        ,NVL2(ES1.SCHOOLCLASSNAME,ES1.SCHOOLCLASSNAME,EPS.SCHOOLCLASSNAME) SCHOOLCLASSNAMEFULL
        ,ESY.SCHOOLYEARNAME
        ,ESY.SCHOOLYEARID SCHOOLYEAR_ID
        ,ESY.FROMYEAR SCHOOLYEARINDEX
        ,(CASE WHEN ep.SUBJECTASSESSTYPEID = 1 THEN
          REPLACE(rtrim(to_char(EPM.FIRSTTERMMARK, 'FM90.099'),',' ),'.',',')
          ELSE DECODE(EPM.FIRSTTERMMARK,0 ,'CÐ',1,'Ð',2,'M','' ) END ) FIRSTTERMMARK
        ,(CASE WHEN ep.SUBJECTASSESSTYPEID = 1 THEN
          REPLACE(rtrim(to_char(EPM.SECONDTERMMARK, 'FM90.099'),',' ),'.',',')
          ELSE DECODE(EPM.SECONDTERMMARK,0 ,'CÐ',1,'Ð',2,'M','' ) END )SECONDTERMMARK
        ,(CASE WHEN ep.SUBJECTASSESSTYPEID = 1 THEN
          REPLACE(rtrim(to_char(EPM.WHOLEYEARMARK, 'FM90.099'),',' ),'.',',')
          ELSE DECODE(EPM.WHOLEYEARMARK,0 ,'CÐ',1,'Ð',2,'M','' ) END )WHOLEYEARMARK
        ,REPLACE(rtrim(to_char(EPS.FIRSTTERMAVERAGEMARK, 'FM90.099'),',' ),'.',',') FIRSTTERMAVERAGEMARK
        ,REPLACE(rtrim(to_char(EPS.SECONDTERMAVERAGEMARK, 'FM90.099'),',' ),'.',',') SECONDTERMAVERAGEMARK
        ,REPLACE(rtrim(to_char(EPS.WHOLEYEARAVERAGEMARK, 'FM90.099'),',' ),'.',',') WHOLEYEARAVERAGEMARK

        ,NVL(SAMS.GETPUPILPOLOBJECTNAMELIST_INFO( EP.PUPILID),'..............................................................................................................') POLICYOBJECTLIST
--        ,GETTOTALCHANGEMARKBOOK(EP.PUPILID,EPS.SCHOOLYEARID,EPS.SCHOOLCLASSID) TOTALCHANGEMARKBOOK
--        ,GETCHANGEMARKBOOKSUBJECTLIST(EP.PUPILID,EPS.SCHOOLYEARID,EPS.SCHOOLCLASSID) TOTALCHANGESUBJECTLIST
        ,EDU_SUBJECTSECTION.SUBJECTSECTIONNAME
        ,SAMS.GETTOTALATTENDANCE(EP.PUPILID,2,-1,EPS.SCHOOLYEARID) COUNTATT_PER
        ,SAMS.GETTOTALATTENDANCE(EP.PUPILID,3,-1,EPS.SCHOOLYEARID) COUNTATT_NOPER
        ,SAMS.GETTOTALATTENDANCE(EP.PUPILID,2,-1,EPS.SCHOOLYEARID) + SAMS.GETTOTALATTENDANCE(EP.PUPILID,3,-1,EPS.SCHOOLYEARID) ABSENTCOUNT
        ,EDU_STUDYBOOKINFO.CITIZENEDUCATIONSUBJECTREMARK
        ,EP.SUBJECTID
        ,ep.ORDERINDEX SUBJECTINDEX
        ,DECODE(-1,-1,DECODE(EP.SUBJECTID,8,'                ' || NVL(TEACHER.FULLNAME,TEACHER1.FULLNAME) ||chr(13) || NVL(EDU_STUDYBOOKINFO.citizeneducationsubjectremark,'........................................................................................................................................') ,'                ' || NVL(TEACHER.FULLNAME,TEACHER1.FULLNAME)),NVL2(TEACHER.FULLNAME,'               ' ||TEACHER.FULLNAME,'               ' ||TEACHER1.FULLNAME)) TEACHERFULLNAME
--        ,'                  '||NVL(TEACHER.FULLNAME,TEACHER1.FULLNAME) TEACHERFULLNAME
        ,ep.ORDERINDEX
        ,NVL(EDU_STUDYBOOKINFO.PRIZECONTENT,(DECODE(NVL(ec.educationlevelid,4),3,'................................. ...................................................................................................................................................',4,'....................................................... ...................................................................................................................................................','')))PRIZECONTENT
        ,DECODE(-1,-1,NVL(EDU_STUDYBOOKINFO.OTHERREWARD,'................................................................................................... ...................................................................................................................................................'),NVL(EDU_STUDYBOOKINFO.OTHERREWARD,'............................................................................................................. ...................................................................................................................................................')) OTHERREWARD
        --,EPS.HEADTEACHERREMARKCONTENT
        --,EPS.PRINCIPALAPPROVECONTENT
        ,EDU_STUDYBOOKINFO.PRINCIPALCOMMENT PRINCIPALAPPROVECONTENT
        ,NVL2(EDU_STUDYBOOKINFO.PRINCIPALAPPROVEDATE,'ngày '||TO_CHAR( TO_TIMESTAMP(EDU_STUDYBOOKINFO.PRINCIPALAPPROVEDATE),'DD') || ' tháng ' || TO_CHAR( TO_TIMESTAMP(EDU_STUDYBOOKINFO.PRINCIPALAPPROVEDATE),'MM') || ' nam ' || TO_CHAR( TO_TIMESTAMP(EDU_STUDYBOOKINFO.PRINCIPALAPPROVEDATE),'YYYY'),'ngày..........tháng..........nam 20........') PRINCIPALAPPROVEDATE
        ,SAMS.EDU_PASSCLASSTYPE.ISPASSCLASS
        ,DECODE(SAMS.EDU_PASSCLASSTYPE.ISPASSCLASS,1,0,1)
        ,(CASE WHEN edu_passclasstype.ispassclass = 1 AND passclasspupil.ispassclass =1
      THEN (
        CASE
          WHEN TO_NUMBER(trim(regexp_replace(EDU_CLASS.CLASSNAME, '[[:alpha:]]|_'))) = 12 THEN 'Ð? di?u ki?n d? thi THPT Qu?c Gia'
          WHEN TO_NUMBER(trim(regexp_replace(EDU_CLASS.CLASSNAME, '[[:alpha:]]|_'))) = 9 THEN 'Ð? di?u ki?n xét TN'
          ELSE 'Ðu?c lên l?p '|| TO_NUMBER(trim(regexp_replace(EDU_CLASS.CLASSNAME, '[[:alpha:]]|_')) + 1) END
      )
           WHEN EDU_PASSCLASSTYPE.PASSCLASSTYPEID = NULL THEN
          nvl(EDU_STUDYBOOKINFO.PASSCLASSCOMMENT,'....................................')
          ELSE '....................................' END ) PASSCLASSCOMMENT
        ,(CASE WHEN edu_passclasstype.ispassclass = 0 AND passclasspupil.ispassclass = 1 THEN
          'Không du?c lên l?p '
      || TO_NUMBER(trim(regexp_replace(EDU_CLASS.CLASSNAME, '[[:alpha:]]|_')) + 1)
          WHEN EDU_PASSCLASSTYPE.PASSCLASSTYPEID = NULL THEN
          NVL(EDU_STUDYBOOKINFO.NOPASSCLASSCOMMENT,'....................................')
          ELSE '....................................' END ) NOPASSCLASSCOMMENT
        ,DECODE(OCCUPATIONSUBJECT1.SUBJECTNAME,NULL,NVL(OCCUPATIONSUBJECT.SUBJECTNAME,'......................................................'),NVL(OCCUPATIONSUBJECT1.SUBJECTNAME,'......................................................'))OCCUPATIONSUBJECTNAME
        ,DECODE(EDU_OCCUPATIONRESULT1.OCCUPATIONRESULTNAME,NULL,NVL(EDU_OCCUPATIONRESULT.OCCUPATIONRESULTNAME,'..............................'),NVL(EDU_OCCUPATIONRESULT1.OCCUPATIONRESULTNAME,'................................')) OCCUPATIONRESULTNAME
        ,SAMS.EDU_SCHOOLCLASS_SUBJECT.ISBILINGUALSUBJECT

        /*Câ?p nhâ?t phâ`n xê´p loa?i khi thi la?i 31/08/2018*/
        ,RECHECKCONDUCTRANK.CONDUCTRANKNAME RECHECKCONDUCTRANKNAME
        ,CASE WHEN UPPER(RECHECKSTUDYRANK.STUDYRANKNAME) = 'GI?I' THEN 'Trung bình'
             WHEN UPPER(RECHECKSTUDYRANK.STUDYRANKNAME) = 'KHÁ' THEN 'Trung bình'
             -- WHEN RECHECKSTUDYRANK.STUDYRANKNAME = 'KHÁ' THEN 'Trung bình'
              
              ELSE TO_CHAR(RECHECKSTUDYRANK.STUDYRANKNAME)
         END RECHECKSTUDYRANKNAME

        ,EDU_PASSCLASSTYPE.ISPASSCLASS EDU_PASSCLASSTYPEISPASSCLASS
        ,PASSCLASSPUPIL.ISPASSCLASS PASSCLASSPUPILISPASSCLASS
        ,EDU_CLASS.CLASSNAME
        ,EDU_CLASS.CLASSID
        ,EPS.RECHECKAVERAGEMARK
        ,DECODE(RECHECKCONDUCTRANK.CONDUCTRANKID,NULL,0,1) ISRETRAIN
        ,NVL((SELECT 1 FROM SAMS.EDU_PUPIL_RECHECKSUBJECT
  WHERE
      SAMS.EDU_PUPIL_RECHECKSUBJECT.PUPILID = EP.PUPILID
  AND EDU_PUPIL_RECHECKSUBJECT.SCHOOLCLASSID = EPS.SCHOOLCLASSID
  AND EDU_PUPIL_RECHECKSUBJECT.SCHOOLYEARID = EPS.SCHOOLYEARID
  AND EDU_PUPIL_RECHECKSUBJECT.ISACTIVE = 1
  AND EDU_PUPIL_RECHECKSUBJECT.ISDELETED =0
  AND ROWNUM = 1),0) ISRECHECK

       ,EDU_STUDYBOOKINFO.PRINCIPALFULLNAME
       ,NVL2(EDU_STUDYBOOKINFO.PRINCIPALSIGNDATE,'ngày '||TO_CHAR( EDU_STUDYBOOKINFO.PRINCIPALSIGNDATE,'DD') || ' tháng ' || TO_CHAR( EDU_STUDYBOOKINFO.PRINCIPALSIGNDATE,'MM') || ' nam ' || TO_CHAR( EDU_STUDYBOOKINFO.PRINCIPALSIGNDATE,'YYYY'),'ngày..........tháng..........nam 20........') PRINCIPALSIGNDATE
       ,EDU_STUDYBOOKINFO.HEADTEACHERFULLNAME
       ,EDU_STUDYBOOKINFO.REGISTERBOOKNUMBER
       ,NVL(ES1.SCHOOLCLASSID,0) SCHOOLCLASSID
       ,EC.ORDERINDEX CLASSINDEX
       ,ES1.ORDERINDEX SCHOOLCLASSINDEX
       ,EP.CURRENTPUPILSTATUSID
       ,CASE
    WHEN WHOLEYEARSTUDYRANKID = 1 AND (WHOLEYEARCONDUCTRANKID = 1 OR WHOLEYEARCONDUCTRANKID = 5) THEN 'Gi?i' || DECODE(SAMS.EDU_STUDYBOOKINFO.PRIZECONTENT,NULL,'','; ' || TO_CHAR(SAMS.EDU_STUDYBOOKINFO.PRIZECONTENT))
    WHEN WHOLEYEARSTUDYRANKID IN (2, 1) AND  (WHOLEYEARCONDUCTRANKID IN (1, 2 ) OR WHOLEYEARCONDUCTRANKID = 5) THEN 'Tiên ti?n' || DECODE(SAMS.EDU_STUDYBOOKINFO.PRIZECONTENT,NULL,'','; ' || TO_CHAR(SAMS.EDU_STUDYBOOKINFO.PRIZECONTENT))
    ELSE '..................................................................................................................'
  END AS SIGNIFICATION
        ,1 WHOLEYEARSTUDYRANKID
        ,1 WHOLEYEARCONDUCTRANKID

        ,EDU_STUDYBOOKINFO.BEGINTERMDATE,
        EDU_STUDYBOOKINFO.ENDTERMDATE

      FROM 
      
      (
          SELECT DISTINCT EP.pupilid,eps1.schoolyearid,eps1.schoolid,eps1.schoolclassid,ess1.subjectid,eps1.currentpupilstatusid,eps1.schooltermid,
                          ep.PLACEOFBIRTHPROVINCEID,ep.placeofbirthcountryid,ep.ETHNICITYID,
                          ep.FATHERJOBID,ep.motherjobid,ep.guardianjobid,ep.fatherjobtitle,ep.motherjobtitle,ep.guardianjobtitle,
                          ep.fatherfullname,ep.motherfullname,ep.guardianfullname,
                          EP.WARDID,ep.FULLNAME,ep.gender,ep.FULLADDRESS,ep.birthday,
                          es.orderindex,es.subjectname,es.subjectassesstypeid
              FROM      SAMS.EDU_PUPIL EP
              JOIN      SAMS.EDU_PUPIL_STUDYTIMELINE EPS1
                ON      EP.PUPILID            =   EPS1.PUPILID
                        AND EPS1.SCHOOLTERMID = 2
                        AND EPS1.ISDELETED    = 0
                        AND EPS1.ISACTIVE     = 1
              LEFT
              JOIN SAMS.edu_schoolclass_subject ess1
                    ON      ess1.SCHOOLCLASSID    = EPS1.SCHOOLCLASSID
                            AND ess1.schoolyearid = EPS1.schoolyearid
                            AND ess1.ISDELETED = 0
               LEFT
                JOIN      sams.edu_subject es ON ess1.subjectid = es.subjectid
                AND       es.isdeleted = 0 AND es.isactive = 1
                WHERE     ep.pupilid IN (011100154)
                          AND EP.ISACTIVE   = 1
                          AND EP.ISDELETED  = 0
                          AND eps1.ISACTIVE   = 1
                          AND EPs1.ISDELETED  = 0
                          AND EPS1.SCHOOLTERMID = 2
                          AND (EPS1.CURRENTPUPILSTATUSID = 1 OR EPS1.CURRENTPUPILSTATUSID = -1)
                         -- AND EXISTS (SELECT 1 FROM TMP_IDNUMBER4 WHERE TMP_IDNUMBER4.IDNUMBER = EPS1.SCHOOLYEARID)
                          AND EPS1.SCHOOLYEARID = 1
        ) ep
     
      LEFT JOIN SAMS.EDU_PUPIL_STUDYHISTORY EPS
        ON EPS.PUPILID = EP.PUPILID
       AND EPS.SCHOOLCLASSID=ep.SCHOOLCLASSID
        AND EPS.SCHOOLYEARID=ep.SCHOOLYEARID
        AND EPS.ISACTIVE =1
        AND EPS.ISDELETED = 0

      LEFT JOIN SAMS.MD_PROVINCE PLACEOFBIRTHROVINCE
        ON PLACEOFBIRTHROVINCE.PROVINCEID = EP.PLACEOFBIRTHPROVINCEID
      LEFT JOIN SAMS.MD_COUNTRY PLACEOFBIRTHCOUNTRY
        ON PLACEOFBIRTHCOUNTRY.COUNTRYID = EP.PLACEOFBIRTHCOUNTRYID
      LEFT JOIN SAMS.PL_ETHNICITY
        ON PL_ETHNICITY.ETHNICITYID = EP.ETHNICITYID
      LEFT JOIN SAMS.MD_JOB MJF
        ON MJF.JOBID = EP.FATHERJOBID
      LEFT JOIN SAMS.MD_JOB MJM
        ON MJM.JOBID = EP.MOTHERJOBID
      LEFT JOIN SAMS.MD_JOB MJW
        ON MJW.JOBID = EP.GUARDIANJOBID
      -- QUA TRINH HOC TAP
      LEFT JOIN SAMS.EDU_SCHOOLCLASS_NEW ES2
        ON EP.SCHOOLCLASSID = ES2.SCHOOLCLASSID
        AND ES2.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND ES2.schooltermid = EP.SCHOOLTERMID
      LEFT JOIN SAMS.EDU_CLASS EC
        ON EC.CLASSID = ES2.CLASSID --EP.CURRENTCLASSID
        AND EC.ISACTIVE = 1
        AND EC.ISDELETED = 0
        AND EC.EDUCATIONLEVELID = 4
      LEFT JOIN SAMS.EDU_CONDUCTRANK RECHECKCONDUCTRANK
        ON RECHECKCONDUCTRANK.CONDUCTRANKID = EPS.RETRAINCONDUCTRANKID
        AND RECHECKCONDUCTRANK.ISACTIVE = 1
        AND RECHECKCONDUCTRANK.ISDELETED = 0
      LEFT JOIN SAMS.EDU_STUDYRANK RECHECKSTUDYRANK
        ON RECHECKSTUDYRANK.STUDYRANKID = EPS.RECHECKSTUDYRANKID
        AND RECHECKSTUDYRANK.ISACTIVE = 1
        AND RECHECKSTUDYRANK.ISDELETED = 0
      LEFT JOIN SAMS.EDU_SCHOOL ES ON ES.SCHOOLID= EPS.SCHOOLID
        AND ES.ISACTIVE =1 AND ES.ISDELETED = 0
      LEFT JOIN SAMS.MD_DISTRICT MD ON MD.DISTRICTID=ES.DISTRICTID
        AND MD.ISACTIVE =1 AND MD.ISDELETED = 0
      LEFT JOIN SAMS.MD_PROVINCE MP ON MP.PROVINCEID= ES.PROVINCEID
        AND MP.ISACTIVE =1 AND MP.ISDELETED = 0
      LEFT JOIN SAMS.EDU_CONDUCTRANK EC1 
      ON EC1.CONDUCTRANKID= EPS.FIRSTTERMCONDUCTRANKID
        AND EC1.ISACTIVE =1 AND EC1.ISDELETED = 0
      LEFT JOIN SAMS.EDU_CONDUCTRANK EC2 ON EC2.CONDUCTRANKID= EPS.SECONDTERMCONDUCTRANKID
        AND EC2.ISACTIVE =1 AND EC2.ISDELETED = 0
      LEFT JOIN SAMS.EDU_CONDUCTRANK EC3 ON EC3.CONDUCTRANKID= EPS.WHOLEYEARCONDUCTRANKID
        AND EC3.ISACTIVE =1 AND EC3.ISDELETED = 0
      LEFT JOIN SAMS.EDU_CONDUCTRANK EC4 ON EC4.CONDUCTRANKID= EPS.RETRAINCONDUCTRANKID
        AND EC4.ISACTIVE =1 AND EC4.ISDELETED = 0
      LEFT JOIN SAMS.SYS_USER SU ON SU.USERNAME=EPS.HEADTEACHERUSER
        AND SU.ISACTIVE =1 AND SU.ISDELETED = 0

      LEFT JOIN SAMS.EDU_SCHOOLCLASS_HEADTEACHER
        ON EDU_SCHOOLCLASS_HEADTEACHER.SCHOOLCLASSID = EP.SCHOOLCLASSID
        AND EDU_SCHOOLCLASS_HEADTEACHER.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND EDU_SCHOOLCLASS_HEADTEACHER.SCHOOLTERMID = 2
        AND EDU_SCHOOLCLASS_HEADTEACHER.ISDELETED = 0
--
        LEFT JOIN SAMS.SYS_USER HEADTEACHERUSER
      ON HEADTEACHERUSER.USERNAME=SAMS.EDU_SCHOOLCLASS_HEADTEACHER.HEADTEACHER
        AND HEADTEACHERUSER.ISACTIVE =1 AND HEADTEACHERUSER.ISDELETED = 0
      LEFT JOIN SAMS.SYS_USER SUPRINCIPAL ON SUPRINCIPAL.USERNAME=EPS.PRINCIPALUSER
        AND SUPRINCIPAL.ISACTIVE =1 AND SUPRINCIPAL.ISDELETED = 0
      LEFT JOIN sams.md_organ SCHOOLORGAN
        ON SCHOOLORGAN.organid = ES.organid
      LEFT JOIN SAMS.MD_WARD
        ON EP.WARDID = MD_WARD.WARDID
      LEFT JOIN SAMS.MD_DISTRICT SCHOOLORGANDISTRICT
        ON SCHOOLORGANDISTRICT.DISTRICTID=SCHOOLORGAN.districtid
        AND SCHOOLORGANDISTRICT.ISACTIVE =1 AND SCHOOLORGANDISTRICT.ISDELETED = 0
       LEFT JOIN SAMS.MD_WARD SCHOOLORGANWARD
        ON SCHOOLORGANWARD.WARDID=SCHOOLORGAN.wardid
        AND SCHOOLORGANWARD.ISACTIVE =1 AND SCHOOLORGANWARD.ISDELETED = 0
      LEFT JOIN SAMS.MD_PROVINCE SCHOOLORGANPROVINCE
        ON SCHOOLORGANPROVINCE.PROVINCEID= SCHOOLORGAN.provinceid
        AND SCHOOLORGANPROVINCE.ISACTIVE =1 AND SCHOOLORGANPROVINCE.ISDELETED = 0
    LEFT JOIN SAMS.EDU_PUPIL_MARK EPM
      ON EPM.PUPILID = EP.PUPILID
      AND EPM.SUBJECTID = ep.SUBJECTID
--      AND EPM.ISACTIVE = 1
      AND EPM.ISDELETED = 0
      AND EPM.SCHOOLCLASSID = EP.SCHOOLCLASSID
      AND EPM.SCHOOLYEARID = EP.SCHOOLYEARID
    LEFT JOIN SAMS.EDU_SCHOOLYEAR ESY ON ESY.SCHOOLYEARID= EPS.SCHOOLYEARID
    LEFT JOIN sams.EDU_SCHOOLCLASS_NEW ES1 
          ON ES1.SCHOOLCLASSID= EPS.SCHOOLCLASSID--EPS.SCHOOLCLASSID
          AND ES1.SCHOOLYEARID = EPS.SCHOOLYEARID
          AND ES1.SCHOOLTERMID = EP.SCHOOLTERMID
    LEFT JOIN SAMS.EDU_SUBJECTSECTION
        ON EDU_SUBJECTSECTION.SUBJECTSECTIONID = ES1.SUBJECTSECTIONID
    LEFT JOIN SAMS.EDU_SCHOOLCLASS_TEACHER
        ON SAMS.EDU_SCHOOLCLASS_TEACHER.SUBJECTID = EP.SUBJECTID
        AND SAMS.EDU_SCHOOLCLASS_TEACHER.SCHOOLCLASSID = EPS.SCHOOLCLASSID
        AND SAMS.EDU_SCHOOLCLASS_TEACHER.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND SAMS.EDU_SCHOOLCLASS_TEACHER.SCHOOLTERMID = 2
        AND SAMS.EDU_SCHOOLCLASS_TEACHER.ISDELETED = 0
     LEFT JOIN SAMS.SYS_USER TEACHER
        ON TEACHER.USERNAME = EDU_SCHOOLCLASS_TEACHER.TEACHER

      LEFT JOIN SAMS.EDU_SCHOOLCLASS_TEACHER SCHOOLCLASS_TEACHER1
        ON SAMS.SCHOOLCLASS_TEACHER1.SUBJECTID = EP.SUBJECTID
        AND SAMS.SCHOOLCLASS_TEACHER1.SCHOOLCLASSID = EPS.SCHOOLCLASSID
        AND SAMS.SCHOOLCLASS_TEACHER1.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND SAMS.SCHOOLCLASS_TEACHER1.SCHOOLTERMID = 1
        AND SAMS.SCHOOLCLASS_TEACHER1.ISDELETED = 0
     LEFT JOIN SAMS.SYS_USER TEACHER1
        ON TEACHER1.USERNAME = SCHOOLCLASS_TEACHER1.TEACHER

     LEFT JOIN SAMS.EDU_STUDYBOOKINFO
        ON EDU_STUDYBOOKINFO.PUPILID = EP.PUPILID
        AND EDU_STUDYBOOKINFO.SCHOOLCLASSID = EPS.SCHOOLCLASSID
        AND EDU_STUDYBOOKINFO.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND EDU_STUDYBOOKINFO.ISDELETED =0

      LEFT JOIN
      (
        SELECT
          EPPT.PASSCLASSTYPEID
          ,EPPT.PUPILID
          ,EPT.CLASSID
          ,EPT.ISPASSCLASS
          ,EPT.SCHOOLYEARID
        FROM SAMS.EDU_PASSCLASSREQUEST_PUPIL EPPT
        JOIN SAMS.EDU_PASSCLASSREQUEST EPT
              ON EPT.PASSCLASSREQUESTID = EPPT.PASSCLASSREQUESTID
        WHERE EPT.ISDELETED = 0
--          AND EPT.SCHOOLYEARID = V_SCHOOLYEARID
          --AND EXISTS (SELECT 1 FROM TMP_IDNUMBER4 WHERE TMP_IDNUMBER4.IDNUMBER = EPT.SCHOOLYEARID )
           AND EPT.SCHOOLYEARID in (1)
          --AND EXISTS (SELECT 1 FROM TMP_IDNUMBER3 WHERE TMP_IDNUMBER3.IDNUMBER = EPPT.PUPILID )
          --AND EPPT.PUPILID IN (SELECT TMP_IDNUMBER3.IDNUMBER FROM TMP_IDNUMBER3)
          AND EPPT.PUPILID IN (011100154)
          AND EPT.ISPASSCLASS = 1
      ) PASSCLASSPUPIL ON EP.PUPILID = PASSCLASSPUPIL.PUPILID
      AND PASSCLASSPUPIL.SCHOOLYEARID = EPS.SCHOOLYEARID
     LEFT JOIN SAMS.edu_passclasstype
        ON edu_passclasstype.passclasstypeid = passclasspupil.PASSCLASSTYPEID

     LEFT JOIN SAMS.EDU_CLASS
        ON EDU_CLASS.CLASSID = passclasspupil.CLASSID
     LEFT JOIN SAMS.EDU_PUPIL_OCCUPATIONSUBJECT
        ON EDU_PUPIL_OCCUPATIONSUBJECT.PUPILID = EP.PUPILID
        AND EDU_PUPIL_OCCUPATIONSUBJECT.SCHOOLCLASSID = EPS.SCHOOLCLASSID--eps1.schoolclassid --EP.CURRENTSCHOOLCLASSID
        AND EDU_PUPIL_OCCUPATIONSUBJECT.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND EDU_PUPIL_OCCUPATIONSUBJECT.SCHOOLTERMID = 2
     LEFT JOIN SAMS.EDU_SUBJECT OCCUPATIONSUBJECT
        ON OCCUPATIONSUBJECT.SUBJECTID = EDU_PUPIL_OCCUPATIONSUBJECT.SUBJECTID
          LEFT JOIN SAMS.EDU_OCCUPATIONRESULT
        ON EDU_OCCUPATIONRESULT.OCCUPATIONRESULTID = EDU_PUPIL_OCCUPATIONSUBJECT.OCCUPATIONRESULTID
       LEFT JOIN SAMS.EDU_PUPIL_OCCUPATIONSUBJECT EDU_PUPIL_OCCUPATIONSUBJECT1
        ON EDU_PUPIL_OCCUPATIONSUBJECT1.PUPILID = EP.PUPILID
        AND EDU_PUPIL_OCCUPATIONSUBJECT1.SCHOOLCLASSID = EPS.SCHOOLCLASSID--eps1.schoolclassid --EP.CURRENTSCHOOLCLASSID
        AND EDU_PUPIL_OCCUPATIONSUBJECT1.SCHOOLYEARID = EPS.SCHOOLYEARID
        AND EDU_PUPIL_OCCUPATIONSUBJECT1.SCHOOLTERMID = 1
     LEFT JOIN SAMS.EDU_SUBJECT OCCUPATIONSUBJECT1
        ON OCCUPATIONSUBJECT1.SUBJECTID = EDU_PUPIL_OCCUPATIONSUBJECT1.SUBJECTID
      LEFT JOIN SAMS.EDU_OCCUPATIONRESULT EDU_OCCUPATIONRESULT1
        ON EDU_OCCUPATIONRESULT1.OCCUPATIONRESULTID = EDU_PUPIL_OCCUPATIONSUBJECT1.OCCUPATIONRESULTID
     LEFT JOIN
      SAMS.EDU_SCHOOLCLASS_SUBJECT
        ON
      EDU_SCHOOLCLASS_SUBJECT.SUBJECTID = EPM.SUBJECTID
        AND
      EDU_SCHOOLCLASS_SUBJECT.SCHOOLCLASSID = EPS.SCHOOLCLASSID
        AND EDU_SCHOOLCLASS_SUBJECT.SCHOOLYEARID = EPS.SCHOOLYEARID
      ) TEMP
     LEFT JOIN
      SAMS.EDU_PUPIL_RECHECKSUBJECT
        ON
        SAMS.EDU_PUPIL_RECHECKSUBJECT.PUPILID = TEMP.PUPILID
        --AND EXISTS (SELECT 1 FROM TMP_IDNUMBER4 WHERE TMP_IDNUMBER4.IDNUMBER = SAMS.EDU_PUPIL_RECHECKSUBJECT.SCHOOLYEARID )
         AND SAMS.EDU_PUPIL_RECHECKSUBJECT.SCHOOLYEARID =1
        AND SAMS.EDU_PUPIL_RECHECKSUBJECT.SCHOOLCLASSID = TEMP.SCHOOLCLASSID
        AND SAMS.EDU_PUPIL_RECHECKSUBJECT.SUBJECTID = TEMP.SUBJECTID
        AND SAMS.EDU_PUPIL_RECHECKSUBJECT.ISACTIVE = 1
        AND SAMS.EDU_PUPIL_RECHECKSUBJECT.ISDELETED = 0
        AND SAMS.EDU_PUPIL_RECHECKSUBJECT.RECHECKMARK IS NOT NULL